org.gradle.jvmargs=-Xmx1G
loom.ignoreDependencyLoomVersionValidation=true
minecraft_version=1.21.3
enabled_platforms=fabric,neoforge
archives_base_name=eternalstarlight
mod_version=0.1.17
maven_group=cn.leolezury
fabric_loader_version=0.16.7
fabric_api_version=0.106.1+1.21.3
neoforge_version=21.3.3-beta