package cn.leolezury.eternalstarlight.common.client.model.animation;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;


@Environment(EnvType.CLIENT)
public class StarlightGolemAnimation {
    public static final AnimationDefinition BEAM = AnimationDefinition.Builder.withLength(10.708344f)
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(3.1676665f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5834335f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.6766665f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7916765f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.875f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9583435f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.041677f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.125f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.208343f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.343333f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.416767f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.5f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.583433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.676667f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.75f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.875f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.958343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.041677f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.083433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.167667f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.25f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.375f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.458343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.541677f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.583433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.676667f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.75f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.875f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.958343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.041677f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.125f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.208343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.291677f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.416767f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.5f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.583433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(8.541676f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(9.167666f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(9.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.75f, KeyframeAnimations.degreeVec(-12.49f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(9f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(10f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(3.1676665f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5416765f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.625f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.8343335f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9167665f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.083433f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.167667f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.375f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.458343f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.625f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.708343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.916767f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.125f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.208343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.416767f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.5f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.625f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.708343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.916767f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.167667f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.25f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.458343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.541677f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.625f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7083435f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.8343335f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9167665f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.083433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.167667f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.25f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.375f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.458343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.541677f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.625f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.708343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.791677f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.916767f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.083433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.125f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.208343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.291677f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.416767f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.5f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.583433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.625f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.708343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.791677f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.916767f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.083433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.167667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.25f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.343333f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.458343f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.541677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.625f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(8.541676f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(9.167666f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(9.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(10f, 5f, 20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-70f, -20f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(-190f, 120f, -85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 50f, 110f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.708343f, KeyframeAnimations.degreeVec(50f, 35f, 120f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(8.416766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(9.25f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(10f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(3.2083435f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5834335f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.6766665f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.875f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9583435f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.125f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.208343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.416767f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.5f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.676667f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.75f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.958343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.041677f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.167667f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.25f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.458343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.541677f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.676667f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.75f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.958343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.041677f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.208343f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.291677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.5f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.583433f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(3.5834335f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.6766665f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.75f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.875f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9583435f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.041677f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.125f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.208343f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.291677f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.416767f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.5f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.583433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.676667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.75f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.834333f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.958343f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.041677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.125f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.167667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.25f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.343333f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.458343f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.541677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.625f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.676667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.75f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.834333f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.958343f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.041677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.125f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.208343f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.291677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.375f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.5f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.583433f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.676667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(8.541676f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(9.167666f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(9.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(10f, -5f, -20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-70f, 20f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(-190f, -120f, 85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7f, KeyframeAnimations.degreeVec(0f, -50f, -110f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.708343f, KeyframeAnimations.degreeVec(50f, -35f, -120f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(8.416766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(9.25f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(10f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(3.2083435f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.625f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7083435f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9167665f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.167667f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.25f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.458343f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.541677f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.708343f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.791677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.083433f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.208343f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.291677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.5f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.583433f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.708343f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.791677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.083433f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.25f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.343333f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.541677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.625f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.0834333f, KeyframeAnimations.posVec(0f, -1f, -1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.1676665f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.625f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7083435f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7916765f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9167665f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.083433f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.167667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.25f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.343333f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.458343f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.541677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.625f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.791677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.875f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.083433f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.167667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.208343f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.291677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.375f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.5f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.583433f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.676667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.708343f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.791677f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.875f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.083433f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.167667f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.25f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.343333f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.416767f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.541677f, KeyframeAnimations.posVec(-1f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.625f, KeyframeAnimations.posVec(1f, 2f, 0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.708343f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(40f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.7916765f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.5f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(8f, KeyframeAnimations.degreeVec(40f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(9f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(10f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(3.3433335f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.6766665f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.75f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9583435f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.041677f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.208343f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.291677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.5f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.583433f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.75f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.834333f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.041677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.125f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.25f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.343333f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.541677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.625f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.75f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.834333f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.041677f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.125f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.291677f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.375f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.583433f, KeyframeAnimations.scaleVec(1.02f, 1.02f, 1.02f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.676667f, KeyframeAnimations.scaleVec(0.98f, 0.98f, 0.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6.75f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition FLAME = AnimationDefinition.Builder.withLength(1.5f).looping()
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 1f, -1.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(25f, 15f, 25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-55f, -5f, -20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-150f, -10f, -40f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-190f, -10f, -40f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 1f, -1.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(25f, -15f, -25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-55f, 5f, 20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-150f, 10f, 40f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-190f, 10f, 40f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4167667f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.625f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition POWER_START = AnimationDefinition.Builder.withLength(1f)
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, -2.5f, 3f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 2f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 4f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(15f, 0f, 15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 2f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 4f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(15f, 0f, -15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("base",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition POWER_END = AnimationDefinition.Builder.withLength(1.5f)
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, -2.5f, 3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 1f, 3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, KeyframeAnimations.posVec(0f, 0f, 3f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.125f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 2f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-12f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 2f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-12f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("base",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition POWER = AnimationDefinition.Builder.withLength(0.5f).looping()
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, -2.5f, 3f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("base",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition DEATH = AnimationDefinition.Builder.withLength(5f)
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(15f, 20f, 10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-20f, -5f, -20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(40f, 5f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(40f, 5f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.875f, KeyframeAnimations.degreeVec(25f, 5f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(-15f, 5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.75f, KeyframeAnimations.degreeVec(85f, 5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -1f, -2f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(10f, 30f, 20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(20f, 20f, 35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(-70f, -5f, 10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(-70f, -5f, 10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(-80f, -5f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.291677f, KeyframeAnimations.degreeVec(-30f, 20f, 15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.791677f, KeyframeAnimations.degreeVec(10f, 20f, 15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(0f, 20f, 15f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -1f, -2f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(15f, -25f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(35f, 10f, -30f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(-70f, 10f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(-70f, 10f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(-80f, 10f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.291677f, KeyframeAnimations.degreeVec(-20f, -20f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.75f, KeyframeAnimations.degreeVec(10f, -20f, -25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(0f, -20f, -25f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.2916765f, KeyframeAnimations.posVec(0f, 2f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-40f, 0f, 20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(50f, 10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.2083435f, KeyframeAnimations.degreeVec(50f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.75f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.25f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.676667f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.958343f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition SHAKE_GROUND = AnimationDefinition.Builder.withLength(3f)
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-40f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(40f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(40f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7083433f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(20f, -15f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-220f, -20f, -20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-105f, -10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-115f, -10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7083433f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_arm",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(20f, 15f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-220f, 20f, 20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-105f, 10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-115f, 10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
}
