package cn.leolezury.eternalstarlight.forge.datagen.provider.tags;

import cn.leolezury.eternalstarlight.common.EternalStarlight;
import cn.leolezury.eternalstarlight.common.registry.ESBlocks;
import cn.leolezury.eternalstarlight.common.util.ESTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ESBlockTagsProvider extends BlockTagsProvider {
    public ESBlockTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, EternalStarlight.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider lookupProvider) {
        // mod tags
        tag(ESTags.Blocks.LUNAR_LOGS).add(
                ESBlocks.LUNAR_LOG.get(),
                ESBlocks.LUNAR_WOOD.get(),
                ESBlocks.STRIPPED_LUNAR_LOG.get(),
                ESBlocks.DEAD_LUNAR_LOG.get(),
                ESBlocks.RED_CRYSTALLIZED_LUNAR_LOG.get(),
                ESBlocks.BLUE_CRYSTALLIZED_LUNAR_LOG.get()
        );
        tag(ESTags.Blocks.NORTHLAND_LOGS).add(
                ESBlocks.NORTHLAND_LOG.get(),
                ESBlocks.NORTHLAND_WOOD.get(),
                ESBlocks.STRIPPED_NORTHLAND_LOG.get(),
                ESBlocks.STRIPPED_NORTHLAND_WOOD.get()
        );
        tag(ESTags.Blocks.STARLIGHT_MANGROVE_LOGS).add(
                ESBlocks.STARLIGHT_MANGROVE_LOG.get(),
                ESBlocks.STARLIGHT_MANGROVE_WOOD.get(),
                ESBlocks.STRIPPED_STARLIGHT_MANGROVE_LOG.get(),
                ESBlocks.STRIPPED_STARLIGHT_MANGROVE_WOOD.get()
        );
        tag(ESTags.Blocks.SCARLET_LOGS).add(
                ESBlocks.SCARLET_LOG.get(),
                ESBlocks.SCARLET_WOOD.get(),
                ESBlocks.STRIPPED_SCARLET_LOG.get(),
                ESBlocks.STRIPPED_SCARLET_WOOD.get()
        );
        tag(ESTags.Blocks.TORREYA_LOGS).add(
                ESBlocks.TORREYA_LOG.get(),
                ESBlocks.TORREYA_WOOD.get(),
                ESBlocks.STRIPPED_TORREYA_LOG.get(),
                ESBlocks.STRIPPED_TORREYA_WOOD.get()
        );
        tag(ESTags.Blocks.PORTAL_FRAME_BLOCKS).add(
                ESBlocks.CHISELED_VOIDSTONE.get()
        );
        tag(ESTags.Blocks.BASE_STONE_STARLIGHT).add(
                ESBlocks.GRIMSTONE.get(),
                ESBlocks.VOIDSTONE.get(),
                Blocks.STONE,
                Blocks.DEEPSLATE
        );
        tag(ESTags.Blocks.CORAL_PLANTS).add(
                ESBlocks.TENTACLES_CORAL.get(),
                ESBlocks.GOLDEN_CORAL.get(),
                ESBlocks.CRYSTALLUM_CORAL.get()
        );
        tag(ESTags.Blocks.CORALS).addTag(ESTags.Blocks.CORAL_PLANTS).add(
                ESBlocks.TENTACLES_CORAL_FAN.get(),
                ESBlocks.GOLDEN_CORAL_FAN.get(),
                ESBlocks.CRYSTALLUM_CORAL_FAN.get()
        );
        tag(ESTags.Blocks.WALL_CORALS).add(
                ESBlocks.TENTACLES_CORAL_WALL_FAN.get(),
                ESBlocks.GOLDEN_CORAL_WALL_FAN.get(),
                ESBlocks.CRYSTALLUM_CORAL_WALL_FAN.get()
        );
        tag(ESTags.Blocks.CORAL_BLOCKS).add(
                ESBlocks.TENTACLES_CORAL_BLOCK.get(),
                ESBlocks.GOLDEN_CORAL_BLOCK.get(),
                ESBlocks.CRYSTALLUM_CORAL_BLOCK.get()
        );
        tag(ESTags.Blocks.YETI_FUR).add(
                ESBlocks.WHITE_YETI_FUR.get(),
                ESBlocks.ORANGE_YETI_FUR.get(),
                ESBlocks.MAGENTA_YETI_FUR.get(),
                ESBlocks.LIGHT_BLUE_YETI_FUR.get(),
                ESBlocks.YELLOW_YETI_FUR.get(),
                ESBlocks.LIME_YETI_FUR.get(),
                ESBlocks.PINK_YETI_FUR.get(),
                ESBlocks.GRAY_YETI_FUR.get(),
                ESBlocks.LIGHT_GRAY_YETI_FUR.get(),
                ESBlocks.CYAN_YETI_FUR.get(),
                ESBlocks.PURPLE_YETI_FUR.get(),
                ESBlocks.BLUE_YETI_FUR.get(),
                ESBlocks.BROWN_YETI_FUR.get(),
                ESBlocks.GREEN_YETI_FUR.get(),
                ESBlocks.RED_YETI_FUR.get(),
                ESBlocks.BLACK_YETI_FUR.get()
        );
        tag(ESTags.Blocks.YETI_FUR_CARPETS).add(
                ESBlocks.WHITE_YETI_FUR_CARPET.get(),
                ESBlocks.ORANGE_YETI_FUR_CARPET.get(),
                ESBlocks.MAGENTA_YETI_FUR_CARPET.get(),
                ESBlocks.LIGHT_BLUE_YETI_FUR_CARPET.get(),
                ESBlocks.YELLOW_YETI_FUR_CARPET.get(),
                ESBlocks.LIME_YETI_FUR_CARPET.get(),
                ESBlocks.PINK_YETI_FUR_CARPET.get(),
                ESBlocks.GRAY_YETI_FUR_CARPET.get(),
                ESBlocks.LIGHT_GRAY_YETI_FUR_CARPET.get(),
                ESBlocks.CYAN_YETI_FUR_CARPET.get(),
                ESBlocks.PURPLE_YETI_FUR_CARPET.get(),
                ESBlocks.BLUE_YETI_FUR_CARPET.get(),
                ESBlocks.BROWN_YETI_FUR_CARPET.get(),
                ESBlocks.GREEN_YETI_FUR_CARPET.get(),
                ESBlocks.RED_YETI_FUR_CARPET.get(),
                ESBlocks.BLACK_YETI_FUR_CARPET.get()
        );
        // mc tags
        tag(BlockTags.OVERWORLD_CARVER_REPLACEABLES).addTag(ESTags.Blocks.BASE_STONE_STARLIGHT);
        tag(BlockTags.LOGS).addTags(
                ESTags.Blocks.LUNAR_LOGS,
                ESTags.Blocks.NORTHLAND_LOGS,
                ESTags.Blocks.STARLIGHT_MANGROVE_LOGS,
                ESTags.Blocks.SCARLET_LOGS,
                ESTags.Blocks.TORREYA_LOGS
        );
        tag(BlockTags.LOGS_THAT_BURN).addTags(
                ESTags.Blocks.LUNAR_LOGS,
                ESTags.Blocks.NORTHLAND_LOGS,
                ESTags.Blocks.STARLIGHT_MANGROVE_LOGS,
                ESTags.Blocks.SCARLET_LOGS,
                ESTags.Blocks.TORREYA_LOGS
        );
        tag(BlockTags.SAPLINGS).add(
                ESBlocks.LUNAR_SAPLING.get(),
                ESBlocks.NORTHLAND_SAPLING.get(),
                ESBlocks.STARLIGHT_MANGROVE_SAPLING.get(),
                ESBlocks.SCARLET_SAPLING.get(),
                ESBlocks.TORREYA_SAPLING.get()
        );
        tag(BlockTags.LEAVES).add(
                ESBlocks.LUNAR_LEAVES.get(),
                ESBlocks.NORTHLAND_LEAVES.get(),
                ESBlocks.STARLIGHT_MANGROVE_LEAVES.get(),
                ESBlocks.SCARLET_LEAVES.get(),
                ESBlocks.TORREYA_LEAVES.get()
        );
        tag(BlockTags.PLANKS).add(
                ESBlocks.LUNAR_PLANKS.get(),
                ESBlocks.NORTHLAND_PLANKS.get(),
                ESBlocks.STARLIGHT_MANGROVE_PLANKS.get(),
                ESBlocks.SCARLET_PLANKS.get(),
                ESBlocks.TORREYA_PLANKS.get()
        );
        tag(BlockTags.WOODEN_FENCES).add(
                ESBlocks.LUNAR_FENCE.get(),
                ESBlocks.NORTHLAND_FENCE.get(),
                ESBlocks.STARLIGHT_MANGROVE_FENCE.get(),
                ESBlocks.SCARLET_FENCE.get(),
                ESBlocks.TORREYA_FENCE.get(),
                ESBlocks.LUNAR_MOSAIC_FENCE.get()
        );
        tag(BlockTags.FENCE_GATES).add(
                ESBlocks.LUNAR_FENCE_GATE.get(),
                ESBlocks.NORTHLAND_FENCE_GATE.get(),
                ESBlocks.STARLIGHT_MANGROVE_FENCE_GATE.get(),
                ESBlocks.SCARLET_FENCE_GATE.get(),
                ESBlocks.TORREYA_FENCE_GATE.get(),
                ESBlocks.LUNAR_MOSAIC_FENCE_GATE.get()
        );
        tag(BlockTags.WOODEN_SLABS).add(
                ESBlocks.LUNAR_SLAB.get(),
                ESBlocks.NORTHLAND_SLAB.get(),
                ESBlocks.STARLIGHT_MANGROVE_SLAB.get(),
                ESBlocks.SCARLET_SLAB.get(),
                ESBlocks.TORREYA_SLAB.get(),
                ESBlocks.LUNAR_MOSAIC_SLAB.get()
        );
        tag(BlockTags.SLABS).add(
                ESBlocks.COBBLED_GRIMSTONE_SLAB.get(),
                ESBlocks.GRIMSTONE_BRICK_SLAB.get(),
                ESBlocks.POLISHED_GRIMSTONE_SLAB.get(),
                ESBlocks.GRIMSTONE_TILE_SLAB.get(),
                ESBlocks.COBBLED_VOIDSTONE_SLAB.get(),
                ESBlocks.VOIDSTONE_BRICK_SLAB.get(),
                ESBlocks.POLISHED_VOIDSTONE_SLAB.get(),
                ESBlocks.VOIDSTONE_TILE_SLAB.get(),
                ESBlocks.POLISHED_ABYSSLATE_SLAB.get(),
                ESBlocks.POLISHED_ABYSSLATE_BRICK_SLAB.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_SLAB.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_BRICK_SLAB.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_SLAB.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_BRICK_SLAB.get(),
                ESBlocks.NIGHTSHADE_MUD_BRICK_SLAB.get(),
                ESBlocks.TWILIGHT_SANDSTONE_SLAB.get(),
                ESBlocks.CUT_TWILIGHT_SANDSTONE_SLAB.get(),
                ESBlocks.DUSTED_BRICK_SLAB.get(),
                ESBlocks.GOLEM_STEEL_SLAB.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_SLAB.get(),
                ESBlocks.GOLEM_STEEL_TILE_SLAB.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_TILE_SLAB.get(),
                ESBlocks.DOOMEDEN_BRICK_SLAB.get(),
                ESBlocks.POLISHED_DOOMEDEN_BRICK_SLAB.get(),
                ESBlocks.DOOMEDEN_TILE_SLAB.get()
        );
        tag(BlockTags.WOODEN_STAIRS).add(
                ESBlocks.LUNAR_STAIRS.get(),
                ESBlocks.NORTHLAND_STAIRS.get(),
                ESBlocks.STARLIGHT_MANGROVE_STAIRS.get(),
                ESBlocks.SCARLET_STAIRS.get(),
                ESBlocks.TORREYA_STAIRS.get(),
                ESBlocks.LUNAR_MOSAIC_STAIRS.get()
        );
        tag(BlockTags.STAIRS).add(
                ESBlocks.COBBLED_GRIMSTONE_STAIRS.get(),
                ESBlocks.GRIMSTONE_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_GRIMSTONE_STAIRS.get(),
                ESBlocks.GRIMSTONE_TILE_STAIRS.get(),
                ESBlocks.COBBLED_VOIDSTONE_STAIRS.get(),
                ESBlocks.VOIDSTONE_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_VOIDSTONE_STAIRS.get(),
                ESBlocks.VOIDSTONE_TILE_STAIRS.get(),
                ESBlocks.POLISHED_ABYSSLATE_STAIRS.get(),
                ESBlocks.POLISHED_ABYSSLATE_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_STAIRS.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_STAIRS.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_BRICK_STAIRS.get(),
                ESBlocks.NIGHTSHADE_MUD_BRICK_STAIRS.get(),
                ESBlocks.TWILIGHT_SANDSTONE_STAIRS.get(),
                ESBlocks.CUT_TWILIGHT_SANDSTONE_STAIRS.get(),
                ESBlocks.DUSTED_BRICK_STAIRS.get(),
                ESBlocks.GOLEM_STEEL_STAIRS.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_STAIRS.get(),
                ESBlocks.GOLEM_STEEL_TILE_STAIRS.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_TILE_STAIRS.get(),
                ESBlocks.DOOMEDEN_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_DOOMEDEN_BRICK_STAIRS.get(),
                ESBlocks.DOOMEDEN_TILE_STAIRS.get()
        );
        tag(BlockTags.WALLS).add(
                ESBlocks.COBBLED_GRIMSTONE_WALL.get(),
                ESBlocks.GRIMSTONE_BRICK_WALL.get(),
                ESBlocks.POLISHED_GRIMSTONE_WALL.get(),
                ESBlocks.GRIMSTONE_TILE_WALL.get(),
                ESBlocks.COBBLED_VOIDSTONE_WALL.get(),
                ESBlocks.VOIDSTONE_BRICK_WALL.get(),
                ESBlocks.POLISHED_VOIDSTONE_WALL.get(),
                ESBlocks.VOIDSTONE_TILE_WALL.get(),
                ESBlocks.POLISHED_ABYSSLATE_WALL.get(),
                ESBlocks.POLISHED_ABYSSLATE_BRICK_WALL.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_WALL.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_BRICK_WALL.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_WALL.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_BRICK_WALL.get(),
                ESBlocks.NIGHTSHADE_MUD_BRICK_WALL.get(),
                ESBlocks.TWILIGHT_SANDSTONE_WALL.get(),
                ESBlocks.CUT_TWILIGHT_SANDSTONE_WALL.get(),
                ESBlocks.DUSTED_BRICK_WALL.get(),
                ESBlocks.DOOMEDEN_BRICK_WALL.get(),
                ESBlocks.POLISHED_DOOMEDEN_BRICK_WALL.get(),
                ESBlocks.DOOMEDEN_TILE_WALL.get()
        );
        tag(BlockTags.WOODEN_BUTTONS).add(
                ESBlocks.LUNAR_BUTTON.get(),
                ESBlocks.NORTHLAND_BUTTON.get(),
                ESBlocks.STARLIGHT_MANGROVE_BUTTON.get(),
                ESBlocks.SCARLET_BUTTON.get(),
                ESBlocks.TORREYA_BUTTON.get()
        );
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(
                ESBlocks.LUNAR_PRESSURE_PLATE.get(),
                ESBlocks.NORTHLAND_PRESSURE_PLATE.get(),
                ESBlocks.STARLIGHT_MANGROVE_PRESSURE_PLATE.get(),
                ESBlocks.SCARLET_PRESSURE_PLATE.get(),
                ESBlocks.TORREYA_PRESSURE_PLATE.get()
        );
        tag(BlockTags.WOODEN_DOORS).add(
                ESBlocks.LUNAR_DOOR.get(),
                ESBlocks.NORTHLAND_DOOR.get(),
                ESBlocks.STARLIGHT_MANGROVE_DOOR.get(),
                ESBlocks.SCARLET_DOOR.get(),
                ESBlocks.TORREYA_DOOR.get()
        );
        tag(BlockTags.WOODEN_TRAPDOORS).add(
                ESBlocks.LUNAR_TRAPDOOR.get(),
                ESBlocks.NORTHLAND_TRAPDOOR.get(),
                ESBlocks.STARLIGHT_MANGROVE_TRAPDOOR.get(),
                ESBlocks.SCARLET_TRAPDOOR.get(),
                ESBlocks.TORREYA_TRAPDOOR.get()
        );
        tag(BlockTags.SMALL_FLOWERS).add(
                ESBlocks.STARLIGHT_FLOWER.get(),
                ESBlocks.CONEBLOOM.get(),
                ESBlocks.NIGHTFAN.get(),
                ESBlocks.PINK_ROSE.get(),
                ESBlocks.STARLIGHT_TORCHFLOWER.get(),
                ESBlocks.WHISPERBLOOM.get(),
                ESBlocks.SWAMP_ROSE.get(),
                ESBlocks.WITHERED_STARLIGHT_FLOWER.get()
        );
        tag(BlockTags.FLOWER_POTS).add(
                ESBlocks.POTTED_LUNAR_SAPLING.get(),
                ESBlocks.POTTED_NORTHLAND_SAPLING.get(),
                ESBlocks.POTTED_STARLIGHT_MANGROVE_SAPLING.get(),
                ESBlocks.POTTED_SCARLET_SAPLING.get(),
                ESBlocks.POTTED_TORREYA_SAPLING.get(),
                ESBlocks.POTTED_STARLIGHT_FLOWER.get(),
                ESBlocks.POTTED_SWAMP_ROSE.get()
        );
        tag(BlockTags.PORTALS).add(
                ESBlocks.STARLIGHT_PORTAL.get()
        );
        tag(BlockTags.CLIMBABLE).add(
                ESBlocks.BERRIES_VINES.get(),
                ESBlocks.BERRIES_VINES_PLANT.get(),
                ESBlocks.CAVE_MOSS.get(),
                ESBlocks.CAVE_MOSS_PLANT.get(),
                ESBlocks.CAVE_MOSS_VEIN.get(),
                ESBlocks.TORREYA_VINES.get(),
                ESBlocks.TORREYA_VINES_PLANT.get()
        );
        tag(BlockTags.STANDING_SIGNS).add(
                ESBlocks.LUNAR_SIGN.get(),
                ESBlocks.NORTHLAND_SIGN.get(),
                ESBlocks.STARLIGHT_MANGROVE_SIGN.get(),
                ESBlocks.SCARLET_SIGN.get(),
                ESBlocks.TORREYA_SIGN.get()
        );
        tag(BlockTags.WALL_SIGNS).add(
                ESBlocks.LUNAR_WALL_SIGN.get(),
                ESBlocks.NORTHLAND_WALL_SIGN.get(),
                ESBlocks.STARLIGHT_MANGROVE_WALL_SIGN.get(),
                ESBlocks.SCARLET_WALL_SIGN.get(),
                ESBlocks.TORREYA_WALL_SIGN.get()
        );
        tag(BlockTags.CEILING_HANGING_SIGNS).add(
                ESBlocks.LUNAR_HANGING_SIGN.get(),
                ESBlocks.NORTHLAND_HANGING_SIGN.get(),
                ESBlocks.STARLIGHT_MANGROVE_HANGING_SIGN.get(),
                ESBlocks.SCARLET_HANGING_SIGN.get(),
                ESBlocks.TORREYA_HANGING_SIGN.get()
        );
        tag(BlockTags.WALL_HANGING_SIGNS).add(
                ESBlocks.LUNAR_WALL_HANGING_SIGN.get(),
                ESBlocks.NORTHLAND_WALL_HANGING_SIGN.get(),
                ESBlocks.STARLIGHT_MANGROVE_WALL_HANGING_SIGN.get(),
                ESBlocks.SCARLET_WALL_HANGING_SIGN.get(),
                ESBlocks.TORREYA_WALL_HANGING_SIGN.get()
        );
        tag(BlockTags.BEACON_BASE_BLOCKS).add(
                ESBlocks.AETHERSENT_BLOCK.get(),
                ESBlocks.SWAMP_SILVER_BLOCK.get(),
                ESBlocks.GOLEM_STEEL_BLOCK.get()
        );
        tag(BlockTags.DIRT).add(
                ESBlocks.NIGHTSHADE_DIRT.get(),
                ESBlocks.NIGHTSHADE_MUD.get(),
                ESBlocks.GLOWING_NIGHTSHADE_MUD.get(),
                ESBlocks.NIGHTSHADE_GRASS_BLOCK.get(),
                ESBlocks.FANTASY_GRASS_BLOCK.get()
        );
        tag(BlockTags.SAND).add(
                ESBlocks.TWILIGHT_SAND.get()
        );
        tag(BlockTags.SMELTS_TO_GLASS).add(
                ESBlocks.TWILIGHT_SAND.get()
        );
        tag(BlockTags.MUSHROOM_GROW_BLOCK).add(
                ESBlocks.NIGHTSHADE_GRASS_BLOCK.get(),
                ESBlocks.NIGHTSHADE_DIRT.get()
        );
        tag(BlockTags.WITHER_IMMUNE).add(
                ESBlocks.ENERGY_BLOCK.get()
        );
        tag(BlockTags.DRAGON_IMMUNE).add(
                ESBlocks.ENERGY_BLOCK.get()
        );
        tag(BlockTags.MOSS_REPLACEABLE).add(
                ESBlocks.GRIMSTONE.get(),
                ESBlocks.VOIDSTONE.get()
        );
        tag(BlockTags.CANDLES).add(
                ESBlocks.AMARAMBER_CANDLE.get()
        );

        // mc tools stuff
        tag(BlockTags.MINEABLE_WITH_PICKAXE).add(
                ESBlocks.AETHERSENT_BLOCK.get(),
                ESBlocks.SWAMP_SILVER_BLOCK.get(),
                ESBlocks.SPRINGSTONE.get(),
                ESBlocks.THERMAL_SPRINGSTONE.get(),
                ESBlocks.GRIMSTONE_REDSTONE_ORE.get(),
                ESBlocks.VOIDSTONE_REDSTONE_ORE.get(),
                ESBlocks.GRIMSTONE_SALTPETER_ORE.get(),
                ESBlocks.VOIDSTONE_SALTPETER_ORE.get(),
                ESBlocks.SALTPETER_BLOCK.get(),
                ESBlocks.RED_STARLIGHT_CRYSTAL_BLOCK.get(),
                ESBlocks.BLUE_STARLIGHT_CRYSTAL_BLOCK.get(),
                ESBlocks.RED_STARLIGHT_CRYSTAL_CLUSTER.get(),
                ESBlocks.BLUE_STARLIGHT_CRYSTAL_CLUSTER.get(),
                ESBlocks.TENTACLES_CORAL.get(),
                ESBlocks.GOLDEN_CORAL.get(),
                ESBlocks.CRYSTALLUM_CORAL.get(),
                ESBlocks.TENTACLES_CORAL_FAN.get(),
                ESBlocks.GOLDEN_CORAL_FAN.get(),
                ESBlocks.CRYSTALLUM_CORAL_FAN.get(),
                ESBlocks.TENTACLES_CORAL_WALL_FAN.get(),
                ESBlocks.GOLDEN_CORAL_WALL_FAN.get(),
                ESBlocks.CRYSTALLUM_CORAL_WALL_FAN.get(),
                ESBlocks.TENTACLES_CORAL_BLOCK.get(),
                ESBlocks.GOLDEN_CORAL_BLOCK.get(),
                ESBlocks.CRYSTALLUM_CORAL_BLOCK.get(),
                // all stone building blocks
                ESBlocks.GRIMSTONE.get(),
                ESBlocks.COBBLED_GRIMSTONE.get(),
                ESBlocks.COBBLED_GRIMSTONE_SLAB.get(),
                ESBlocks.COBBLED_GRIMSTONE_STAIRS.get(),
                ESBlocks.COBBLED_GRIMSTONE_WALL.get(),
                ESBlocks.GRIMSTONE_BRICKS.get(),
                ESBlocks.GRIMSTONE_BRICK_SLAB.get(),
                ESBlocks.GRIMSTONE_BRICK_STAIRS.get(),
                ESBlocks.GRIMSTONE_BRICK_WALL.get(),
                ESBlocks.POLISHED_GRIMSTONE.get(),
                ESBlocks.POLISHED_GRIMSTONE_SLAB.get(),
                ESBlocks.POLISHED_GRIMSTONE_STAIRS.get(),
                ESBlocks.POLISHED_GRIMSTONE_WALL.get(),
                ESBlocks.GRIMSTONE_TILES.get(),
                ESBlocks.GRIMSTONE_TILE_SLAB.get(),
                ESBlocks.GRIMSTONE_TILE_STAIRS.get(),
                ESBlocks.GRIMSTONE_TILE_WALL.get(),
                ESBlocks.CHISELED_GRIMSTONE.get(),
                ESBlocks.GLOWING_GRIMSTONE.get(),
                ESBlocks.VOIDSTONE.get(),
                ESBlocks.COBBLED_VOIDSTONE.get(),
                ESBlocks.COBBLED_VOIDSTONE_SLAB.get(),
                ESBlocks.COBBLED_VOIDSTONE_STAIRS.get(),
                ESBlocks.COBBLED_VOIDSTONE_WALL.get(),
                ESBlocks.VOIDSTONE_BRICKS.get(),
                ESBlocks.VOIDSTONE_BRICK_SLAB.get(),
                ESBlocks.VOIDSTONE_BRICK_STAIRS.get(),
                ESBlocks.VOIDSTONE_BRICK_WALL.get(),
                ESBlocks.POLISHED_VOIDSTONE.get(),
                ESBlocks.POLISHED_VOIDSTONE_SLAB.get(),
                ESBlocks.POLISHED_VOIDSTONE_STAIRS.get(),
                ESBlocks.POLISHED_VOIDSTONE_WALL.get(),
                ESBlocks.VOIDSTONE_TILES.get(),
                ESBlocks.VOIDSTONE_TILE_SLAB.get(),
                ESBlocks.VOIDSTONE_TILE_STAIRS.get(),
                ESBlocks.VOIDSTONE_TILE_WALL.get(),
                ESBlocks.CHISELED_VOIDSTONE.get(),
                ESBlocks.GLOWING_VOIDSTONE.get(),
                ESBlocks.ABYSSLATE.get(),
                ESBlocks.POLISHED_ABYSSLATE.get(),
                ESBlocks.POLISHED_ABYSSLATE_SLAB.get(),
                ESBlocks.POLISHED_ABYSSLATE_STAIRS.get(),
                ESBlocks.POLISHED_ABYSSLATE_WALL.get(),
                ESBlocks.POLISHED_ABYSSLATE_BRICKS.get(),
                ESBlocks.POLISHED_ABYSSLATE_BRICK_SLAB.get(),
                ESBlocks.POLISHED_ABYSSLATE_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_ABYSSLATE_BRICK_WALL.get(),
                ESBlocks.CHISELED_POLISHED_ABYSSLATE.get(),
                ESBlocks.ABYSSAL_MAGMA_BLOCK.get(),
                ESBlocks.ABYSSAL_GEYSER.get(),
                ESBlocks.THERMABYSSLATE.get(),
                ESBlocks.POLISHED_THERMABYSSLATE.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_SLAB.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_STAIRS.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_WALL.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_BRICKS.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_BRICK_SLAB.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_THERMABYSSLATE_BRICK_WALL.get(),
                ESBlocks.CHISELED_POLISHED_THERMABYSSLATE.get(),
                ESBlocks.THERMABYSSAL_MAGMA_BLOCK.get(),
                ESBlocks.THERMABYSSAL_GEYSER.get(),
                ESBlocks.CRYOBYSSLATE.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_SLAB.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_STAIRS.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_WALL.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_BRICKS.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_BRICK_SLAB.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_CRYOBYSSLATE_BRICK_WALL.get(),
                ESBlocks.CHISELED_POLISHED_CRYOBYSSLATE.get(),
                ESBlocks.CRYOBYSSAL_MAGMA_BLOCK.get(),
                ESBlocks.CRYOBYSSAL_GEYSER.get(),
                ESBlocks.PACKED_NIGHTSHADE_MUD.get(),
                ESBlocks.NIGHTSHADE_MUD_BRICKS.get(),
                ESBlocks.NIGHTSHADE_MUD_BRICK_SLAB.get(),
                ESBlocks.NIGHTSHADE_MUD_BRICK_STAIRS.get(),
                ESBlocks.NIGHTSHADE_MUD_BRICK_WALL.get(),
                ESBlocks.TWILIGHT_SANDSTONE.get(),
                ESBlocks.TWILIGHT_SANDSTONE_SLAB.get(),
                ESBlocks.TWILIGHT_SANDSTONE_STAIRS.get(),
                ESBlocks.TWILIGHT_SANDSTONE_WALL.get(),
                ESBlocks.CUT_TWILIGHT_SANDSTONE.get(),
                ESBlocks.CUT_TWILIGHT_SANDSTONE_SLAB.get(),
                ESBlocks.CUT_TWILIGHT_SANDSTONE_STAIRS.get(),
                ESBlocks.CUT_TWILIGHT_SANDSTONE_WALL.get(),
                ESBlocks.CHISELED_TWILIGHT_SANDSTONE.get(),
                ESBlocks.DUSTED_BRICKS.get(),
                ESBlocks.DUSTED_BRICK_SLAB.get(),
                ESBlocks.DUSTED_BRICK_STAIRS.get(),
                ESBlocks.DUSTED_BRICK_WALL.get(),
                ESBlocks.GOLEM_STEEL_BLOCK.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_BLOCK.get(),
                ESBlocks.GOLEM_STEEL_SLAB.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_SLAB.get(),
                ESBlocks.GOLEM_STEEL_STAIRS.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_STAIRS.get(),
                ESBlocks.GOLEM_STEEL_TILES.get(),
                ESBlocks.GOLEM_STEEL_TILE_SLAB.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_TILE_SLAB.get(),
                ESBlocks.GOLEM_STEEL_TILE_STAIRS.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_TILE_STAIRS.get(),
                ESBlocks.CHISELED_GOLEM_STEEL_BLOCK.get(),
                ESBlocks.OXIDIZED_CHISELED_GOLEM_STEEL_BLOCK.get(),
                ESBlocks.DOOMEDEN_BRICKS.get(),
                ESBlocks.DOOMEDEN_BRICK_SLAB.get(),
                ESBlocks.DOOMEDEN_BRICK_STAIRS.get(),
                ESBlocks.DOOMEDEN_BRICK_WALL.get(),
                ESBlocks.POLISHED_DOOMEDEN_BRICKS.get(),
                ESBlocks.POLISHED_DOOMEDEN_BRICK_SLAB.get(),
                ESBlocks.POLISHED_DOOMEDEN_BRICK_STAIRS.get(),
                ESBlocks.POLISHED_DOOMEDEN_BRICK_WALL.get(),
                ESBlocks.DOOMEDEN_TILES.get(),
                ESBlocks.DOOMEDEN_TILE_SLAB.get(),
                ESBlocks.DOOMEDEN_TILE_STAIRS.get(),
                ESBlocks.DOOMEDEN_TILE_WALL.get(),
                ESBlocks.CHISELED_POLISHED_DOOMEDEN_BRICKS.get(),
                ESBlocks.CHARGED_CHISELED_POLISHED_DOOMEDEN_BRICKS.get(),
                ESBlocks.DOOMEDEN_KEYHOLE.get(),
                ESBlocks.REDSTONE_DOOMEDEN_KEYHOLE.get()
        );
        tag(BlockTags.MINEABLE_WITH_AXE).add(
                ESBlocks.TORREYA_CAMPFIRE.get(),
                ESBlocks.MOONLIGHT_LILY_PAD.get(),
                ESBlocks.STARLIT_LILY_PAD.get(),
                ESBlocks.MOONLIGHT_DUCKWEED.get()
        );
        tag(BlockTags.MINEABLE_WITH_SHOVEL).add(
                ESBlocks.NIGHTSHADE_DIRT.get(),
                ESBlocks.NIGHTSHADE_MUD.get(),
                ESBlocks.GLOWING_NIGHTSHADE_MUD.get(),
                ESBlocks.TWILIGHT_SAND.get(),
                ESBlocks.DUSTED_GRAVEL.get(),
                ESBlocks.NIGHTSHADE_GRASS_BLOCK.get(),
                ESBlocks.FANTASY_GRASS_BLOCK.get(),
                ESBlocks.SWAMP_SILVER_ORE.get()
        );
        tag(BlockTags.SWORD_EFFICIENT).add(
                ESBlocks.MOONLIGHT_LILY_PAD.get(),
                ESBlocks.STARLIT_LILY_PAD.get(),
                ESBlocks.MOONLIGHT_DUCKWEED.get()
        );
        tag(BlockTags.NEEDS_IRON_TOOL).add(
                ESBlocks.AETHERSENT_BLOCK.get(),
                ESBlocks.SWAMP_SILVER_BLOCK.get(),
                ESBlocks.RED_STARLIGHT_CRYSTAL_BLOCK.get(),
                ESBlocks.BLUE_STARLIGHT_CRYSTAL_BLOCK.get(),
                ESBlocks.RED_STARLIGHT_CRYSTAL_CLUSTER.get(),
                ESBlocks.BLUE_STARLIGHT_CRYSTAL_CLUSTER.get(),
                ESBlocks.GOLEM_STEEL_BLOCK.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_BLOCK.get(),
                ESBlocks.GOLEM_STEEL_SLAB.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_SLAB.get(),
                ESBlocks.GOLEM_STEEL_STAIRS.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_STAIRS.get(),
                ESBlocks.GOLEM_STEEL_TILES.get(),
                ESBlocks.GOLEM_STEEL_TILE_SLAB.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_TILE_SLAB.get(),
                ESBlocks.GOLEM_STEEL_TILE_STAIRS.get(),
                ESBlocks.OXIDIZED_GOLEM_STEEL_TILE_STAIRS.get(),
                ESBlocks.CHISELED_GOLEM_STEEL_BLOCK.get(),
                ESBlocks.OXIDIZED_CHISELED_GOLEM_STEEL_BLOCK.get()
        );
        tag(BlockTags.INSIDE_STEP_SOUND_BLOCKS).add(
                ESBlocks.MOONLIGHT_LILY_PAD.get(),
                ESBlocks.STARLIT_LILY_PAD.get(),
                ESBlocks.MOONLIGHT_DUCKWEED.get()
        );
        tag(BlockTags.FROG_PREFER_JUMP_TO).add(
                ESBlocks.MOONLIGHT_LILY_PAD.get(),
                ESBlocks.STARLIT_LILY_PAD.get(),
                ESBlocks.MOONLIGHT_DUCKWEED.get()
        );
        tag(BlockTags.CAMPFIRES).add(
                ESBlocks.TORREYA_CAMPFIRE.get()
        );
        tag(BlockTags.COMBINATION_STEP_SOUND_BLOCKS).addTag(ESTags.Blocks.YETI_FUR_CARPETS);
        tag(BlockTags.OCCLUDES_VIBRATION_SIGNALS).addTag(ESTags.Blocks.YETI_FUR);
        tag(BlockTags.DAMPENS_VIBRATIONS).addTag(ESTags.Blocks.YETI_FUR).addTag(ESTags.Blocks.YETI_FUR_CARPETS);
    }
}
