package cn.leolezury.eternalstarlight.neoforge.datagen.provider.tags;

import cn.leolezury.eternalstarlight.common.EternalStarlight;
import cn.leolezury.eternalstarlight.common.registry.ESItems;
import cn.leolezury.eternalstarlight.common.util.ESConventionalTags;
import cn.leolezury.eternalstarlight.common.util.ESTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

import java.util.concurrent.CompletableFuture;

public class ESItemTagsProvider extends ItemTagsProvider {
	public ESItemTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> future, CompletableFuture<TagLookup<Block>> provider, ExistingFileHelper helper) {
		super(output, future, provider, EternalStarlight.ID, helper);
	}

	@SuppressWarnings("unchecked")
	@Override
	protected void addTags(HolderLookup.Provider lookupProvider) {
		// conventional tags
		copy(Tags.Blocks.BUDDING_BLOCKS, Tags.Items.BUDDING_BLOCKS);
		copy(Tags.Blocks.BUDS, Tags.Items.BUDS);
		copy(Tags.Blocks.CLUSTERS, Tags.Items.CLUSTERS);
		copy(Tags.Blocks.COBBLESTONES, Tags.Items.COBBLESTONES);
		copy(Tags.Blocks.DYED_BLACK, Tags.Items.DYED_BLACK);
		copy(Tags.Blocks.DYED_BLUE, Tags.Items.DYED_BLUE);
		copy(Tags.Blocks.DYED_BROWN, Tags.Items.DYED_BROWN);
		copy(Tags.Blocks.DYED_CYAN, Tags.Items.DYED_CYAN);
		copy(Tags.Blocks.DYED_GRAY, Tags.Items.DYED_GRAY);
		copy(Tags.Blocks.DYED_GREEN, Tags.Items.DYED_GREEN);
		copy(Tags.Blocks.DYED_LIGHT_BLUE, Tags.Items.DYED_LIGHT_BLUE);
		copy(Tags.Blocks.DYED_LIGHT_GRAY, Tags.Items.DYED_LIGHT_GRAY);
		copy(Tags.Blocks.DYED_LIME, Tags.Items.DYED_LIME);
		copy(Tags.Blocks.DYED_MAGENTA, Tags.Items.DYED_MAGENTA);
		copy(Tags.Blocks.DYED_ORANGE, Tags.Items.DYED_ORANGE);
		copy(Tags.Blocks.DYED_PINK, Tags.Items.DYED_PINK);
		copy(Tags.Blocks.DYED_PURPLE, Tags.Items.DYED_PURPLE);
		copy(Tags.Blocks.DYED_RED, Tags.Items.DYED_RED);
		copy(Tags.Blocks.DYED_WHITE, Tags.Items.DYED_WHITE);
		copy(Tags.Blocks.DYED_YELLOW, Tags.Items.DYED_YELLOW);
		copy(Tags.Blocks.FENCE_GATES_WOODEN, Tags.Items.FENCE_GATES_WOODEN);
		copy(Tags.Blocks.FENCES_WOODEN, Tags.Items.FENCES_WOODEN);
		copy(Tags.Blocks.GRAVELS, Tags.Items.GRAVELS);
		copy(Tags.Blocks.ORE_RATES_DENSE, Tags.Items.ORE_RATES_DENSE);
		copy(Tags.Blocks.ORE_RATES_SPARSE, Tags.Items.ORE_RATES_SPARSE);
		copy(Tags.Blocks.ORES, Tags.Items.ORES);
		copy(Tags.Blocks.ORES_REDSTONE, Tags.Items.ORES_REDSTONE);
		copy(Tags.Blocks.SANDS, Tags.Items.SANDS);
		copy(Tags.Blocks.SANDSTONE_BLOCKS, Tags.Items.SANDSTONE_BLOCKS);
		copy(Tags.Blocks.SANDSTONE_SLABS, Tags.Items.SANDSTONE_SLABS);
		copy(Tags.Blocks.SANDSTONE_STAIRS, Tags.Items.SANDSTONE_STAIRS);
		copy(Tags.Blocks.STONES, Tags.Items.STONES);
		copy(Tags.Blocks.STORAGE_BLOCKS, Tags.Items.STORAGE_BLOCKS);
		copy(Tags.Blocks.STRIPPED_LOGS, Tags.Items.STRIPPED_LOGS);
		copy(Tags.Blocks.STRIPPED_WOODS, Tags.Items.STRIPPED_WOODS);
		tag(Tags.Items.FOODS)
			.add(
				ESItems.JINGLESTEM_CRISP.get(),
				ESItems.JINGLESTEM_SANDWICH.get(),
				ESItems.CRINOA_BALL.get(),
				ESItems.SHADOW_ESCARGOT.get(),
				ESItems.DOOMEDEN_CARRION.get(),
				ESItems.ROTTEN_HAM.get()
			);
		tag(Tags.Items.FOODS_FRUIT)
			.add(
				ESItems.LUNARIS_CACTUS_FRUIT.get(),
				ESItems.LUNARIS_CACTUS_GEL.get(),
				ESItems.ABYSSAL_FRUIT.get(),
				ESItems.VELVETUMOSS_BALL.get(),
				ESItems.PUNGENCY_FRUIT.get(),
				ESItems.SILVER_PUNGENCY_FRUIT.get()
			);
		tag(Tags.Items.FOODS_BERRY)
			.add(
				ESItems.LUNAR_BERRIES.get(),
				ESItems.ABYSSAL_FRUIT.get(),
				ESItems.BLOSSOM_OF_STARS.get()
			);
		tag(Tags.Items.FOODS_RAW_MEAT)
			.add(
				ESItems.ROOKFISH.get(),
				ESItems.AURORA_DEER_STEAK.get(),
				ESItems.RATLIN_MEAT.get(),
				ESItems.SHADOW_SNAIL_MEAT.get()
			);
		tag(Tags.Items.FOODS_COOKED_MEAT)
			.add(
				ESItems.ROTTEN_FLESH_JERKY.get(),
				ESItems.COOKED_ROOKFISH.get(),
				ESItems.COOKED_AURORA_DEER_STEAK.get(),
				ESItems.COOKED_RATLIN_MEAT.get(),
				ESItems.COOKED_SHADOW_SNAIL_MEAT.get()
			);
		tag(Tags.Items.FOODS_RAW_FISH)
			.add(
				ESItems.LUMINOFISH.get(),
				ESItems.LUMINARIS.get()
			);
		tag(Tags.Items.FOODS_COOKED_FISH)
			.add(
				ESItems.COOKED_LUMINOFISH.get(),
				ESItems.COOKED_LUMINARIS.get()
			);
		tag(Tags.Items.FOODS_SOUP)
			.add(
				ESItems.BOULDERSHROOM_STEW.get(),
				ESItems.CRINOA_PORRIDGE.get(),
				ESItems.PUNGENCY_STEW.get()
			);
		tag(Tags.Items.FOODS_PIE)
			.add(
				ESItems.SHADOW_SNAIL_PIE.get()
			);
		tag(Tags.Items.ANIMAL_FOODS)
			.addTags(
				ESTags.Items.AURORA_DEER_FOOD,
				ESTags.Items.CRYSTALLIZED_MOTH_FOOD,
				ESTags.Items.ENT_FOOD,
				ESTags.Items.RATLIN_FOOD,
				ESTags.Items.SHADOW_SNAIL_FOOD,
				ESTags.Items.YETI_FOOD
			);
		tag(Tags.Items.SEEDS)
			.addTags(
				ESConventionalTags.Items.SEEDS_CRINOA,
				ESConventionalTags.Items.SEEDS_PUNGENCY_FRUIT,
				ESConventionalTags.Items.SEEDS_NOCTURNAL_MILLET
			);
		tag(Tags.Items.CROPS)
			.addTags(
				ESConventionalTags.Items.CROPS_CRINOA,
				ESConventionalTags.Items.CROPS_PUNGENCY_FRUIT,
				ESConventionalTags.Items.CROPS_NOCTURNAL_MILLET
			);
		tag(Tags.Items.MUSHROOMS)
			.add(
				ESItems.GLOWING_MUSHROOM.get(),
				ESItems.SHINING_MUSHROOM.get(),
				ESItems.BOULDERSHROOM.get(),
				ESItems.MARIMOLD.get()
			);
		tag(Tags.Items.MUSIC_DISCS)
			.add(
				ESItems.MUSIC_DISC_WHISPER_OF_THE_STARS.get(),
				ESItems.MUSIC_DISC_DUSK_O_EREYESTERDAY.get(),
				ESItems.MUSIC_DISC_TRANQUILITY.get(),
				ESItems.MUSIC_DISC_NEST.get(),
				ESItems.MUSIC_DISC_POSTERITY.get(),
				ESItems.MUSIC_DISC_THE_THORNY_REIGN.get(),
				ESItems.MUSIC_DISC_PROFUNDITY.get(),
				ESItems.MUSIC_DISC_WAILING_WELL.get(),
				ESItems.MUSIC_DISC_STARS_SHINING_UPON_THE_SEA.get(),
				ESItems.MUSIC_DISC_OPTIMIZED_OPTION.get(),
				ESItems.MUSIC_DISC_MECHANICAL_FOSSIL.get(),
				ESItems.MUSIC_DISC_FAKE_LIGHT.get(),
				ESItems.MUSIC_DISC_TRANQUILITY_II.get(),
				ESItems.MUSIC_DISC_ATLANTIS.get(),
				ESItems.MUSIC_DISC_SACRED_DESERT.get(),
				ESItems.MUSIC_DISC_SPIRIT.get(),
				ESItems.MUSIC_DISC_ETHER_RAIN.get(),
				ESItems.MUSIC_DISC_BRISK.get(),
				ESItems.MUSIC_DISC_MOONLIGHT.get()
			);
		tag(Tags.Items.GEMS)
			.add(
				ESItems.RED_STARLIGHT_CRYSTAL_SHARD.get(),
				ESItems.BLUE_STARLIGHT_CRYSTAL_SHARD.get()
			)
			.addTags(
				ESConventionalTags.Items.GEMS_THIOQUARTZ,
				ESConventionalTags.Items.GEMS_GLACITE,
				ESConventionalTags.Items.GEMS_STARLIT_DIAMOND,
				ESConventionalTags.Items.GEMS_MALARITE,
				ESConventionalTags.Items.GEMS_STARCORE
			);
		tag(Tags.Items.GEMS_QUARTZ)
			.add(
				ESItems.THIOQUARTZ_CLUSTER.get()
			);
		tag(Tags.Items.INGOTS)
			.addTags(
				ESConventionalTags.Items.INGOTS_AETHERSENT,
				ESConventionalTags.Items.INGOTS_THERMAL_SPRINGSTONE,
				ESConventionalTags.Items.INGOTS_DEEPSILVER,
				ESConventionalTags.Items.INGOTS_UNREALIUM,
				ESConventionalTags.Items.INGOTS_AMARAMBER,
				ESConventionalTags.Items.INGOTS_GOLEM_STEEL,
				ESConventionalTags.Items.INGOTS_OXIDIZED_GOLEM_STEEL
			);
		tag(Tags.Items.NUGGETS)
			.addTags(
				ESConventionalTags.Items.NUGGETS_AETHERSENT,
				ESConventionalTags.Items.NUGGETS_DEEPSILVER,
				ESConventionalTags.Items.NUGGETS_UNREALIUM,
				ESConventionalTags.Items.NUGGETS_AMARAMBER,
				ESConventionalTags.Items.NUGGETS_GOLEM_STEEL,
				ESConventionalTags.Items.NUGGETS_OXIDIZED_GOLEM_STEEL
			);
		tag(Tags.Items.RAW_MATERIALS)
			.addTags(
				ESConventionalTags.Items.RAW_MATERIALS_AETHERSENT,
				ESConventionalTags.Items.RAW_MATERIALS_AMARAMBER
			);
		tag(Tags.Items.DUSTS)
			.addTags(
				ESConventionalTags.Items.DUSTS_SALTPETER
			);
		tag(Tags.Items.TOOLS_SHIELD)
			.add(
				ESItems.GLACITE_SHIELD.get(),
				ESItems.FLOWGLAZE_SHIELD.get()
			);
		tag(Tags.Items.TOOLS_BOW)
			.add(
				ESItems.STARFALL_LONGBOW.get(),
				ESItems.FLOWGLAZE_BOW.get(),
				ESItems.GLISTERING_BOW.get(),
				ESItems.MOONRING_BOW.get(),
				ESItems.BOW_OF_BLOOD.get()
			);
		tag(Tags.Items.TOOLS_CROSSBOW)
			.add(
				ESItems.UNREALIUM_CROSSBOW.get(),
				ESItems.STARFIRE_CROSSBOW.get(),
				ESItems.MECHANICAL_CROSSBOW.get(),
				ESItems.CRYSTAL_CROSSBOW.get(),
				ESItems.WILTED_CROSSBOW.get()
			);
		tag(Tags.Items.TOOLS_SPEAR)
			.add(
				ESItems.MALARITE_SPEAR.get(),
				ESItems.PUNGENCY_FRUIT_SPEAR.get(),
				ESItems.CRESCENT_SPEAR.get()
			);
		tag(Tags.Items.TOOLS_BRUSH)
			.add(
				ESItems.DEEPSILVER_BRUSH.get()
			);
		tag(Tags.Items.TOOLS_IGNITER)
			.add(
				ESItems.SALTPETER_MATCHBOX.get()
			);
		tag(Tags.Items.MELEE_WEAPON_TOOLS)
			.add(
				ESItems.RAGE_OF_STARS.get(),
				ESItems.THERMAL_SPRINGSTONE_SWORD.get(),
				ESItems.THERMAL_SPRINGSTONE_AXE.get(),
				ESItems.THERMAL_SPRINGSTONE_SCYTHE.get(),
				ESItems.THERMAL_SPRINGSTONE_HAMMER.get(),
				ESItems.GLACITE_SWORD.get(),
				ESItems.GLACITE_AXE.get(),
				ESItems.GLACITE_SCYTHE.get(),
				ESItems.STARLIT_DIAMOND_SWORD.get(),
				ESItems.STARLIT_DIAMOND_AXE.get(),
				ESItems.DEEPSILVER_SWORD.get(),
				ESItems.DEEPSILVER_AXE.get(),
				ESItems.UNREALIUM_SWORD.get(),
				ESItems.UNREALIUM_AXE.get(),
				ESItems.MALARITE_SWORD.get(),
				ESItems.MALARITE_AXE.get(),
				ESItems.PUNGENCY_FRUIT_AXE.get(),
				ESItems.STARFIRE_SWORD.get(),
				ESItems.STARFIRE_AXE.get(),
				ESItems.STARFIRE_SCYTHE.get(),
				ESItems.STARFIRE_HAMMER.get(),
				ESItems.FLOWGLAZE_SWORD.get(),
				ESItems.FLOWGLAZE_AXE.get(),
				ESItems.FLOWGLAZE_SCYTHE.get(),
				ESItems.AMARAMBER_SWORD.get(),
				ESItems.AMARAMBER_AXE.get(),
				ESItems.SHATTERED_SWORD.get(),
				ESItems.DAGGER_OF_HUNGER.get(),
				ESItems.GLISTERING_SWORD.get(),
				ESItems.GLISTERING_GREATSWORD.get(),
				ESItems.GLISTERING_MORNING_STAR.get(),
				ESItems.ENERGY_SWORD.get(),
				ESItems.GOLEM_STEEL_GREATSWORD.get(),
				ESItems.CRYSTAL_GREATSWORD.get(),
				ESItems.MOONRING_GREATSWORD.get(),
				ESItems.PETAL_SCYTHE.get(),
				ESItems.BONEMORE.get(),
				ESItems.DOOMEDEN_RAPIER.get()
			);
		tag(Tags.Items.RANGED_WEAPON_TOOLS)
			.add(
				ESItems.STARFALL_LONGBOW.get(),
				ESItems.UNREALIUM_CROSSBOW.get(),
				ESItems.MALARITE_SPEAR.get(),
				ESItems.PUNGENCY_FRUIT_SPEAR.get(),
				ESItems.SEEDS_LAUNCHER.get(),
				ESItems.STARFIRE_CROSSBOW.get(),
				ESItems.FLOWGLAZE_BOW.get(),
				ESItems.GLISTERING_BOW.get(),
				ESItems.MECHANICAL_CROSSBOW.get(),
				ESItems.CRYSTAL_CROSSBOW.get(),
				ESItems.ENERGY_BOOMERANG.get(),
				ESItems.WILTED_CROSSBOW.get(),
				ESItems.MOONRING_BOW.get(),
				ESItems.CRESCENT_SPEAR.get(),
				ESItems.BOW_OF_BLOOD.get()
			);
		tag(Tags.Items.MINING_TOOL_TOOLS)
			.add(
				ESItems.THERMAL_SPRINGSTONE_PICKAXE.get(),
				ESItems.GLACITE_PICKAXE.get(),
				ESItems.STARLIT_DIAMOND_PICKAXE.get(),
				ESItems.THERMAL_SPRINGSTONE_HAMMER.get(),
				ESItems.DEEPSILVER_PICKAXE.get(),
				ESItems.UNREALIUM_PICKAXE.get(),
				ESItems.MALARITE_PICKAXE.get(),
				ESItems.STARFIRE_HAMMER.get(),
				ESItems.AMARAMBER_PICKAXE.get(),
				ESItems.GLISTERING_MORNING_STAR.get(),
				ESItems.UNDERMINER.get(),
				ESItems.GRAVITY_PICKAXE.get()
			);
		// mod conventional tags
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_CRINOA, ESConventionalTags.Items.STORAGE_BLOCKS_CRINOA);
		copy(ESConventionalTags.Blocks.ORES_STARCORE, ESConventionalTags.Items.ORES_STARCORE);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_STARCORE, ESConventionalTags.Items.STORAGE_BLOCKS_STARCORE);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_RAW_AETHERSENT, ESConventionalTags.Items.STORAGE_BLOCKS_RAW_AETHERSENT);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_AETHERSENT, ESConventionalTags.Items.STORAGE_BLOCKS_AETHERSENT);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_GLACITE, ESConventionalTags.Items.STORAGE_BLOCKS_GLACITE);
		copy(ESConventionalTags.Blocks.ORES_STARLIT_DIAMOND, ESConventionalTags.Items.ORES_STARLIT_DIAMOND);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_STARLIT_DIAMOND, ESConventionalTags.Items.STORAGE_BLOCKS_STARLIT_DIAMOND);
		copy(ESConventionalTags.Blocks.ORES_DEEPSILVER, ESConventionalTags.Items.ORES_DEEPSILVER);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_RAW_DEEPSILVER, ESConventionalTags.Items.STORAGE_BLOCKS_RAW_DEEPSILVER);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_DEEPSILVER, ESConventionalTags.Items.STORAGE_BLOCKS_DEEPSILVER);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_UNREALIUM, ESConventionalTags.Items.STORAGE_BLOCKS_UNREALIUM);
		copy(ESConventionalTags.Blocks.ORES_MALARITE, ESConventionalTags.Items.ORES_MALARITE);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_MALARITE, ESConventionalTags.Items.STORAGE_BLOCKS_MALARITE);
		copy(ESConventionalTags.Blocks.ORES_SALTPETER, ESConventionalTags.Items.ORES_SALTPETER);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_SALTPETER, ESConventionalTags.Items.STORAGE_BLOCKS_SALTPETER);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_RAW_AMARAMBER, ESConventionalTags.Items.STORAGE_BLOCKS_RAW_AMARAMBER);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_GOLEM_STEEL, ESConventionalTags.Items.STORAGE_BLOCKS_GOLEM_STEEL);
		copy(ESConventionalTags.Blocks.STORAGE_BLOCKS_OXIDIZED_GOLEM_STEEL, ESConventionalTags.Items.STORAGE_BLOCKS_OXIDIZED_GOLEM_STEEL);
		copy(ESConventionalTags.Blocks.ORES_IN_GROUND_GRIMSTONE, ESConventionalTags.Items.ORES_IN_GROUND_GRIMSTONE);
		copy(ESConventionalTags.Blocks.ORES_IN_GROUND_VOIDSTONE, ESConventionalTags.Items.ORES_IN_GROUND_VOIDSTONE);
		copy(ESConventionalTags.Blocks.ORES_IN_GROUND_NIGHTFALL_MUD, ESConventionalTags.Items.ORES_IN_GROUND_NIGHTFALL_MUD);
		copy(ESConventionalTags.Blocks.ORES_IN_GROUND_PACKED_NIGHTFALL_MUD, ESConventionalTags.Items.ORES_IN_GROUND_PACKED_NIGHTFALL_MUD);
		tag(ESConventionalTags.Items.SEEDS_CRINOA)
			.add(
				ESItems.CRINOA_SEEDS.get()
			);
		tag(ESConventionalTags.Items.CROPS_CRINOA)
			.add(
				ESItems.CRINOA.get()
			);
		tag(ESConventionalTags.Items.SEEDS_NOCTURNAL_MILLET)
			.add(
				ESItems.NOCTURNAL_MILLET_SEEDS.get()
			);
		tag(ESConventionalTags.Items.CROPS_NOCTURNAL_MILLET)
			.add(
				ESItems.NOCTURNAL_MILLET.get(),
				ESItems.FORGOTTEN_NOCTURNAL_MILLET.get()
			);
		tag(ESConventionalTags.Items.SEEDS_PUNGENCY_FRUIT)
			.add(
				ESItems.PUNGENCY_FRUIT_SEEDS.get()
			);
		tag(ESConventionalTags.Items.CROPS_PUNGENCY_FRUIT)
			.add(
				ESItems.PUNGENCY_FRUIT.get()
			);
		tag(ESConventionalTags.Items.CAMPFIRES)
			.add(
				ESItems.TORREYA_CAMPFIRE.get()
			);
		tag(ESConventionalTags.Items.RAW_MATERIALS_AETHERSENT)
			.add(
				ESItems.RAW_AETHERSENT.get()
			);
		tag(ESConventionalTags.Items.INGOTS_AETHERSENT)
			.add(
				ESItems.AETHERSENT_INGOT.get()
			);
		tag(ESConventionalTags.Items.NUGGETS_AETHERSENT)
			.add(
				ESItems.AETHERSENT_NUGGET.get()
			);
		tag(ESConventionalTags.Items.INGOTS_THERMAL_SPRINGSTONE)
			.add(
				ESItems.THERMAL_SPRINGSTONE_INGOT.get()
			);
		tag(ESConventionalTags.Items.GEMS_GLACITE)
			.add(
				ESItems.GLACITE_SHARD.get()
			);
		tag(ESConventionalTags.Items.GEMS_STARLIT_DIAMOND)
			.add(
				ESItems.STARLIT_DIAMOND.get()
			);
		tag(ESConventionalTags.Items.RAW_MATERIALS_DEEPSILVER)
			.add(
				ESItems.RAW_DEEPSILVER.get()
			);
		tag(ESConventionalTags.Items.INGOTS_DEEPSILVER)
			.add(
				ESItems.DEEPSILVER_INGOT.get()
			);
		tag(ESConventionalTags.Items.NUGGETS_DEEPSILVER)
			.add(
				ESItems.DEEPSILVER_NUGGET.get()
			);
		tag(ESConventionalTags.Items.INGOTS_UNREALIUM)
			.add(
				ESItems.UNREALIUM_INGOT.get()
			);
		tag(ESConventionalTags.Items.NUGGETS_UNREALIUM)
			.add(
				ESItems.UNREALIUM_NUGGET.get()
			);
		tag(ESConventionalTags.Items.GEMS_MALARITE)
			.add(
				ESItems.MALARITE.get()
			);
		tag(ESConventionalTags.Items.DUSTS_SALTPETER)
			.add(
				ESItems.SALTPETER_POWDER.get()
			);
		tag(ESConventionalTags.Items.GEMS_STARCORE)
			.add(
				ESItems.STARCORE.get()
			);
		tag(ESConventionalTags.Items.RAW_MATERIALS_AMARAMBER)
			.add(
				ESItems.RAW_AMARAMBER.get()
			);
		tag(ESConventionalTags.Items.INGOTS_AMARAMBER)
			.add(
				ESItems.AMARAMBER_INGOT.get()
			);
		tag(ESConventionalTags.Items.NUGGETS_AMARAMBER)
			.add(
				ESItems.AMARAMBER_NUGGET.get()
			);
		tag(ESConventionalTags.Items.GEMS_THIOQUARTZ)
			.add(
				ESItems.THIOQUARTZ_SHARD.get()
			);
		tag(ESConventionalTags.Items.INGOTS_GOLEM_STEEL)
			.add(
				ESItems.GOLEM_STEEL_INGOT.get()
			);
		tag(ESConventionalTags.Items.INGOTS_OXIDIZED_GOLEM_STEEL)
			.add(
				ESItems.OXIDIZED_GOLEM_STEEL_INGOT.get()
			);
		tag(ESConventionalTags.Items.NUGGETS_GOLEM_STEEL)
			.add(
				ESItems.GOLEM_STEEL_NUGGET.get()
			);
		tag(ESConventionalTags.Items.NUGGETS_OXIDIZED_GOLEM_STEEL)
			.add(
				ESItems.OXIDIZED_GOLEM_STEEL_NUGGET.get()
			);
		// mod tags
		copy(ESTags.Blocks.LUNAR_LOGS, ESTags.Items.LUNAR_LOGS);
		copy(ESTags.Blocks.NORTHLAND_LOGS, ESTags.Items.NORTHLAND_LOGS);
		copy(ESTags.Blocks.BANYIN_LOGS, ESTags.Items.BANYIN_LOGS);
		copy(ESTags.Blocks.SCARLET_LOGS, ESTags.Items.SCARLET_LOGS);
		copy(ESTags.Blocks.TORREYA_LOGS, ESTags.Items.TORREYA_LOGS);
		copy(ESTags.Blocks.JINGLESTEM_LOGS, ESTags.Items.JINGLESTEM_LOGS);
		copy(ESTags.Blocks.CRADLEWOOD_LOGS, ESTags.Items.CRADLEWOOD_LOGS);
		copy(ESTags.Blocks.YETI_FUR, ESTags.Items.YETI_FUR);
		copy(ESTags.Blocks.YETI_FUR_CARPETS, ESTags.Items.YETI_FUR_CARPETS);
		copy(ESTags.Blocks.TOOTH_OF_HUNGER_BLOCKS, ESTags.Items.TOOTH_OF_HUNGER_BLOCKS);
		tag(ESTags.Items.SCYTHES)
			.add(
				ESItems.THERMAL_SPRINGSTONE_SCYTHE.get(),
				ESItems.GLACITE_SCYTHE.get(),
				ESItems.STARFIRE_SCYTHE.get(),
				ESItems.FLOWGLAZE_SCYTHE.get(),
				ESItems.PETAL_SCYTHE.get()
			);
		tag(ESTags.Items.SICKLES)
			.add(
				ESItems.DEEPSILVER_SICKLE.get(),
				ESItems.UNREALIUM_SICKLE.get(),
				ESItems.MALARITE_SICKLE.get(),
				ESItems.AMARAMBER_SICKLE.get(),
				ESItems.AURORA_DEER_ANTLER.get()
			);
		tag(ESTags.Items.GREATSWORDS)
			.add(
				ESItems.GLISTERING_GREATSWORD.get(),
				ESItems.GOLEM_STEEL_GREATSWORD.get(),
				ESItems.CRYSTAL_GREATSWORD.get(),
				ESItems.MOONRING_GREATSWORD.get(),
				ESItems.BONEMORE.get()
			);
		tag(ESTags.Items.HAMMERS)
			.add(
				ESItems.THERMAL_SPRINGSTONE_HAMMER.get(),
				ESItems.STARFIRE_HAMMER.get(),
				ESItems.GLISTERING_MORNING_STAR.get()
			);
		tag(ESTags.Items.BOOMERANGS)
			.add(
				ESItems.ENERGY_BOOMERANG.get()
			);
		tag(ESTags.Items.WHIPS)
			.add(
				ESItems.CANDLASH.get(),
				ESItems.TENTACLE_SPIKE.get(),
				ESItems.COLDSNAP.get()
			);
		tag(ESTags.Items.SMALL_SHIELDS)
			.add(
				ESItems.GLACITE_SHIELD.get(),
				ESItems.FLOWGLAZE_SHIELD.get()
			);
		tag(ESTags.Items.ACCESSORIES)
			.add(
				ESItems.BATTLEAXE_PENDANT.get(),
				ESItems.WARHAMMER_PENDANT.get(),
				ESItems.BUTTERFLY_WINGS_AMULET.get(),
				ESItems.FUNGUS_AMULET.get(),
				ESItems.PEARL_NECKLACE.get(),
				ESItems.CRESCENT_PENDANT.get()
			);
		tag(ESTags.Items.AURORA_DEER_FOOD)
			.add(
				ESItems.LUNAR_BERRIES.get(),
				ESItems.ABYSSAL_FRUIT.get(),
				ESItems.CRINOA.get()
			);
		tag(ESTags.Items.CRYSTALLIZED_MOTH_FOOD)
			.addTag(ItemTags.MEAT);
		tag(ESTags.Items.STARFIRE_BIRD_FOOD)
			.addTag(Tags.Items.SEEDS)
			.add(
				ESItems.LUNAR_BERRIES.get()
			);
		tag(ESTags.Items.ENT_FOOD)
			.add(
				ESItems.LUNAR_BERRIES.get(),
				ESItems.ABYSSAL_FRUIT.get()
			);
		tag(ESTags.Items.RATLIN_FOOD)
			.add(
				Items.GLOW_LICHEN,
				ESItems.CAVE_MOSS.get(),
				ESItems.CRINOA.get()
			);
		tag(ESTags.Items.SHADOW_SNAIL_FOOD)
			.addTag(ItemTags.LEAVES)
			.add(
				ESItems.LUNAR_BERRIES.get(),
				ESItems.CAVE_MOSS.get()
			);
		tag(ESTags.Items.YETI_FOOD)
			.add(
				ESItems.LUNAR_BERRIES.get(),
				ESItems.CAVE_MOSS.get(),
				ESItems.CRINOA.get()
			);
		tag(ESTags.Items.UNTRIMMABLE_ARMOR)
			.add(
				ESItems.THERMAL_SPRINGSTONE_HELMET.get(),
				ESItems.THERMAL_SPRINGSTONE_CHESTPLATE.get(),
				ESItems.THERMAL_SPRINGSTONE_LEGGINGS.get(),
				ESItems.THERMAL_SPRINGSTONE_BOOTS.get(),
				ESItems.STARLIT_DIAMOND_HELMET.get(),
				ESItems.STARLIT_DIAMOND_CHESTPLATE.get(),
				ESItems.STARLIT_DIAMOND_LEGGINGS.get(),
				ESItems.STARLIT_DIAMOND_BOOTS.get(),
				ESItems.DEEPSILVER_LEGGINGS.get(),
				ESItems.DEEPSILVER_BOOTS.get(),
				ESItems.UNREALIUM_HELMET.get(),
				ESItems.UNREALIUM_CHESTPLATE.get(),
				ESItems.UNREALIUM_LEGGINGS.get(),
				ESItems.UNREALIUM_BOOTS.get(),
				ESItems.AMARAMBER_MASK.get(),
				ESItems.AMARAMBER_CHESTPLATE.get(),
				ESItems.ALCHEMIST_MASK.get(),
				ESItems.ALCHEMIST_ROBE.get(),
				ESItems.AETHERSENT_CAPE.get(),
				ESItems.AETHERSENT_BOTTOMS.get(),
				ESItems.AETHERSENT_BOOTS.get(),
				ESItems.AIR_SAC_MASK.get()
			);
		tag(ESTags.Items.THERMAL_SPRINGSTONE_WEAPONS)
			.add(
				ESItems.THERMAL_SPRINGSTONE_SWORD.get(),
				ESItems.THERMAL_SPRINGSTONE_PICKAXE.get(),
				ESItems.THERMAL_SPRINGSTONE_AXE.get(),
				ESItems.THERMAL_SPRINGSTONE_HOE.get(),
				ESItems.THERMAL_SPRINGSTONE_SHOVEL.get(),
				ESItems.THERMAL_SPRINGSTONE_SCYTHE.get(),
				ESItems.THERMAL_SPRINGSTONE_HAMMER.get()
			);
		tag(ESTags.Items.GLACITE_WEAPONS)
			.add(
				ESItems.GLACITE_SWORD.get(),
				ESItems.GLACITE_PICKAXE.get(),
				ESItems.GLACITE_AXE.get(),
				ESItems.GLACITE_HOE.get(),
				ESItems.GLACITE_SHOVEL.get(),
				ESItems.GLACITE_SCYTHE.get()
			);
		tag(ESTags.Items.MALARITE_WEAPONS)
			.add(
				ESItems.MALARITE_SWORD.get(),
				ESItems.MALARITE_PICKAXE.get(),
				ESItems.MALARITE_AXE.get(),
				ESItems.MALARITE_HOE.get(),
				ESItems.MALARITE_SHOVEL.get(),
				ESItems.MALARITE_SICKLE.get(),
				ESItems.MALARITE_SPEAR.get()
			);
		tag(ESTags.Items.PUNGENCY_FRUIT_WEAPONS)
			.add(
				ESItems.PUNGENCY_FRUIT_AXE.get(),
				ESItems.PUNGENCY_FRUIT_SPEAR.get()
			);
		tag(ESTags.Items.STARFIRE_WEAPONS)
			.add(
				ESItems.STARFIRE_SWORD.get(),
				ESItems.STARFIRE_PICKAXE.get(),
				ESItems.STARFIRE_AXE.get(),
				ESItems.STARFIRE_HOE.get(),
				ESItems.STARFIRE_SHOVEL.get(),
				ESItems.STARFIRE_SCYTHE.get(),
				ESItems.STARFIRE_HAMMER.get()
			);
		tag(ESTags.Items.FLOWGLAZE_WEAPONS)
			.add(
				ESItems.FLOWGLAZE_SWORD.get(),
				ESItems.FLOWGLAZE_PICKAXE.get(),
				ESItems.FLOWGLAZE_AXE.get(),
				ESItems.FLOWGLAZE_HOE.get(),
				ESItems.FLOWGLAZE_SHOVEL.get(),
				ESItems.FLOWGLAZE_SCYTHE.get()
			);
		tag(ESTags.Items.MENDS_NATURALLY)
			.add(
				ESItems.AMARAMBER_SWORD.get(),
				ESItems.AMARAMBER_PICKAXE.get(),
				ESItems.AMARAMBER_AXE.get(),
				ESItems.AMARAMBER_HOE.get(),
				ESItems.AMARAMBER_SHOVEL.get(),
				ESItems.AMARAMBER_SICKLE.get(),
				ESItems.AMARAMBER_MASK.get(),
				ESItems.AMARAMBER_CHESTPLATE.get()
			);
		tag(ESTags.Items.HIDES_WITH_OWNER)
			.add(
				ESItems.UNREALIUM_INGOT.get(),
				ESItems.UNREALIUM_NUGGET.get(),
				ESItems.UNREALIUM_BLOCK.get(),
				ESItems.UNREALIUM_BARS.get(),
				ESItems.UNREALIUM_SWORD.get(),
				ESItems.UNREALIUM_PICKAXE.get(),
				ESItems.UNREALIUM_AXE.get(),
				ESItems.UNREALIUM_HOE.get(),
				ESItems.UNREALIUM_SHOVEL.get(),
				ESItems.UNREALIUM_SICKLE.get(),
				ESItems.UNREALIUM_CROSSBOW.get(),
				ESItems.UNREALIUM_HELMET.get(),
				ESItems.UNREALIUM_CHESTPLATE.get(),
				ESItems.UNREALIUM_LEGGINGS.get(),
				ESItems.UNREALIUM_BOOTS.get()
			);
		tag(ESTags.Items.ALGALEAVES)
			.add(
				ESItems.HANGING_ALGALEAVES.get(),
				ESItems.ALGALEAVES.get()
			);
		tag(ESTags.Items.CRYSTALBORN_CATALYST_FUELS)
			.add(
				ESItems.RED_STARLIGHT_CRYSTAL_SHARD.get(),
				ESItems.BLUE_STARLIGHT_CRYSTAL_SHARD.get()
			);
		tag(ESTags.Items.CONSUMABLE_WHEN_WEARING_FUNGUS_AMULET)
			.addTag(Tags.Items.MUSHROOMS);
		tag(ESTags.Items.REPAIRED_BY_CRESCENT_PENDANT)
			.add(
				ESItems.MOONRING_BOW.get(),
				ESItems.MOONRING_GREATSWORD.get(),
				ESItems.PETAL_SCYTHE.get(),
				ESItems.WAND_OF_TELEPORTATION.get(),
				ESItems.CHAIN_OF_SOULS.get(),
				ESItems.CRESCENT_SPEAR.get()
			);
		tag(ESTags.Items.LUNAR_MONSTROSITY_IGNITERS)
			.add(
				Items.FLINT_AND_STEEL,
				Items.FIRE_CHARGE,
				Items.BLAZE_ROD,
				Items.BLAZE_POWDER,
				ESItems.SALTPETER_MATCHBOX.get(),
				ESItems.THERMAL_SPRINGSTONE_INGOT.get()
			);
		tag(ESTags.Items.STELLAGMITE_IGNITERS)
			.add(
				Items.FLINT_AND_STEEL,
				Items.FIRE_CHARGE,
				Items.BLAZE_ROD,
				Items.BLAZE_POWDER,
				ESItems.SALTPETER_MATCHBOX.get(),
				ESItems.THERMAL_SPRINGSTONE_INGOT.get()
			);
		tag(ESTags.Items.ENT_FERTILIZERS)
			.add(
				Items.BONE_MEAL,
				ESItems.SHADOW_SNAIL_SHELL_POWDER.get()
			);
		tag(ESTags.Items.STRANGHOUL_CAN_USE)
			.add(
				Items.BOW,
				Items.WOODEN_SWORD,
				Items.WOODEN_PICKAXE,
				Items.WOODEN_AXE,
				Items.WOODEN_HOE,
				Items.STONE_SWORD,
				Items.STONE_PICKAXE,
				Items.STONE_AXE,
				Items.STONE_HOE,
				ESItems.MALARITE_SWORD.get(),
				ESItems.MALARITE_PICKAXE.get(),
				ESItems.MALARITE_AXE.get(),
				ESItems.MALARITE_HOE.get(),
				ESItems.MALARITE_SICKLE.get(),
				ESItems.MALARITE_SPEAR.get(),
				ESItems.PUNGENCY_FRUIT_AXE.get(),
				ESItems.PUNGENCY_FRUIT_SPEAR.get(),
				ESItems.SEEDS_LAUNCHER.get()
			);
		tag(ESTags.Items.STRANGHOUL_FOOD)
			.add(
				Items.ROTTEN_FLESH,
				ESItems.PUNGENCY_FRUIT.get(),
				ESItems.PUNGENCY_STEW.get()
			);
		tag(ESTags.Items.STRANGHOUL_HIRING_FOOD)
			.add(
				ESItems.PUNGENCY_STEW.get()
			);
		tag(ESTags.Items.STRANGHOUL_CURRENCIES)
			.add(
				ESItems.MALARITE.get()
			);
		tag(ESTags.Items.STRANGHOUL_VULNERABLE_TO)
			.add(
				ESItems.DEEPSILVER_SWORD.get(),
				ESItems.DEEPSILVER_PICKAXE.get(),
				ESItems.DEEPSILVER_AXE.get(),
				ESItems.DEEPSILVER_SICKLE.get()
			);
		tag(ESTags.Items.SEEDS_LAUNCHER_AMMO)
			.addTag(Tags.Items.SEEDS);
		tag(ESTags.Items.ALLOY_FURNACES)
			.add(
				ESItems.ALLOY_FURNACE.get(),
				ESItems.WAXED_ALLOY_FURNACE.get(),
				ESItems.OXIDIZED_ALLOY_FURNACE.get()
			);
		tag(ESTags.Items.DOOMEDEN_KEYS)
			.add(
				ESItems.EYE_OF_DOOM.get(),
				ESItems.LIVING_ARM.get(),
				ESItems.DOOMEDEN_RAPIER.get()
			);
		tag(ESTags.Items.SCYTHE_ENCHANTABLE)
			.addTag(ESTags.Items.SCYTHES);
		tag(ESTags.Items.GREATSWORD_ENCHANTABLE)
			.addTag(ESTags.Items.GREATSWORDS);
		tag(ESTags.Items.HAMMER_ENCHANTABLE)
			.addTag(ESTags.Items.HAMMERS);
		tag(ESTags.Items.BOOMERANG_ENCHANTABLE)
			.addTag(ESTags.Items.BOOMERANGS);
		tag(ESTags.Items.WHIP_ENCHANTABLE)
			.addTag(ESTags.Items.WHIPS);
		tag(ESTags.Items.CHAIN_OF_SOULS_ENCHANTABLE)
			.add(
				ESItems.CHAIN_OF_SOULS.get()
			);
		tag(ESTags.Items.PUNGENCY_FRUIT_SPEAR_ENCHANTABLE)
			.add(
				ESItems.PUNGENCY_FRUIT_SPEAR.get()
			);
		tag(ESTags.Items.SEEDS_LAUNCHER_ENCHANTABLE)
			.add(
				ESItems.SEEDS_LAUNCHER.get()
			);
		tag(ESTags.Items.CHEST_ARMOR_ACCESSORY_APPLICABLE)
			.addTag(ItemTags.CHEST_ARMOR);
		tag(ESTags.Items.AXE_ACCESSORY_APPLICABLE)
			.addTag(ItemTags.AXES);
		tag(ESTags.Items.HAMMER_ACCESSORY_APPLICABLE)
			.addTag(ESTags.Items.HAMMERS);
		tag(ESTags.Items.AFFECTS_PROGRESSION)
			.add(
				ESItems.PUNGENCY_FRUIT.get(),
				ESItems.SILVER_PUNGENCY_FRUIT.get(),
				ESItems.GOLEM_STEEL_INGOT.get(),
				ESItems.GOLEM_STEEL_NUGGET.get(),
				ESItems.NOCTURNAL_MILLET_SEEDS.get(),
				ESItems.NOCTURNAL_MILLET.get(),
				ESItems.FORGOTTEN_NOCTURNAL_MILLET.get()
			);
		tag(ESTags.Items.GOLEM_FORGE_LOCATORS)
			.add(
				Items.REDSTONE,
				ESItems.OXIDIZED_GOLEM_STEEL_INGOT.get(),
				ESItems.GOLEM_STEEL_INGOT.get()
			);
		tag(ESTags.Items.CURSED_GARDEN_LOCATORS)
			.add(
				Items.VINE,
				ESItems.CAVE_MOSS.get(),
				ESItems.LUNAR_BERRIES.get(),
				ESItems.CAVE_MOSS_BLOCK.get(),
				ESItems.CAVE_MOSS_CARPET.get(),
				ESItems.RED_CRYSTAL_MOSS_BLOCK.get(),
				ESItems.BLUE_CRYSTAL_MOSS_BLOCK.get(),
				ESItems.RED_CRYSTAL_MOSS_CARPET.get(),
				ESItems.BLUE_CRYSTAL_MOSS_CARPET.get(),
				ESItems.RED_CRYSTAL_ROOTS.get(),
				ESItems.BLUE_CRYSTAL_ROOTS.get()
			);
		tag(ESTags.Items.ARROW_FEATHERS)
			.addTag(Tags.Items.FEATHERS)
			.add(
				ESItems.SPIRAL_KELP.get()
			);
		tag(ESTags.Items.MANA_CRYSTAL_INGREDIENTS)
			.add(
				ESItems.RED_STARLIGHT_CRYSTAL_SHARD.get()
			);
		tag(ESTags.Items.MANA_CRYSTALS)
			.addTags(
				ESTags.Items.TERRA_CRYSTALS,
				ESTags.Items.WIND_CRYSTALS,
				ESTags.Items.WATER_CRYSTALS,
				ESTags.Items.LUNAR_CRYSTALS,
				ESTags.Items.BLAZE_CRYSTALS,
				ESTags.Items.LIGHT_CRYSTALS
			);
		tag(ESTags.Items.TERRA_CRYSTAL_INGREDIENTS)
			.add(
				Items.DIRT,
				Items.MUD,
				Items.PODZOL,
				Items.COARSE_DIRT,
				Items.ROOTED_DIRT,
				ESItems.NIGHTFALL_DIRT.get(),
				ESItems.NIGHTFALL_GRASS_BLOCK.get(),
				ESItems.NIGHTFALL_PODZOL.get(),
				ESItems.TENACIOUS_NIGHTFALL_GRASS_BLOCK.get(),
				ESItems.NIGHTFALL_MUD.get(),
				ESItems.GLOWING_NIGHTFALL_MUD.get(),
				ESItems.FANTASY_GRASS_BLOCK.get(),
				ESItems.CONEBLOOM.get()
			);
		tag(ESTags.Items.TERRA_CRYSTALS)
			.add(
				ESItems.TERRA_CRYSTAL.get(),
				ESItems.MANA_CRYSTAL.get()
			);
		tag(ESTags.Items.WIND_CRYSTAL_INGREDIENTS)
			.add(
				Items.WIND_CHARGE,
				Items.BREEZE_ROD,
				ESItems.WHISPERBLOOM.get()
			);
		tag(ESTags.Items.WIND_CRYSTALS)
			.add(
				ESItems.WIND_CRYSTAL.get(),
				ESItems.MANA_CRYSTAL.get()
			);
		tag(ESTags.Items.WATER_CRYSTAL_INGREDIENTS)
			.add(
				Items.ICE,
				Items.PACKED_ICE,
				Items.BLUE_ICE,
				Items.KELP,
				Items.SEAGRASS,
				Items.SEA_PICKLE,
				ESItems.ABYSSAL_FRUIT.get(),
				ESItems.ORBFLORA.get(),
				ESItems.SPIRAL_KELP.get(),
				ESItems.SEA_ROSA.get(),
				ESItems.WICK_GRASS.get(),
				ESItems.LUMENSTEM.get(),
				ESItems.CIRCULUSH.get(),
				ESItems.MARIMOLD.get(),
				ESItems.STONETT.get(),
				ESItems.LUMINIS.get(),
				ESItems.GLOWLIS.get(),
				ESItems.GLOREED.get(),
				ESItems.STARLIGHT_SEAGRASS.get(),
				ESItems.JINGLING_PICKLE.get(),
				ESItems.MOONLIGHT_DUCKWEED.get(),
				ESItems.MOONLIGHT_LILY_PAD.get(),
				ESItems.STARLIT_LILY_PAD.get()
			);
		tag(ESTags.Items.WATER_CRYSTALS)
			.add(
				ESItems.WATER_CRYSTAL.get(),
				ESItems.MANA_CRYSTAL.get()
			);
		tag(ESTags.Items.LUNAR_CRYSTAL_INGREDIENTS)
			.add(
				Items.ENDER_EYE,
				Items.END_STONE,
				ESItems.STARLIGHT_FLOWER.get(),
				ESItems.LUNAR_BERRIES.get(),
				ESItems.LUNAR_GRASS.get(),
				ESItems.GLOWING_LUNAR_GRASS.get(),
				ESItems.LUNAR_REED.get(),
				ESItems.LUNARIS_CACTUS.get(),
				ESItems.LUNARIS_CACTUS_GEL_BLOCK.get(),
				ESItems.LUNARIS_CACTUS_FRUIT.get()
			);
		tag(ESTags.Items.LUNAR_CRYSTALS)
			.add(
				ESItems.LUNAR_CRYSTAL.get(),
				ESItems.MANA_CRYSTAL.get()
			);
		tag(ESTags.Items.BLAZE_CRYSTAL_INGREDIENTS)
			.add(
				Items.BLAZE_ROD,
				Items.BLAZE_POWDER,
				Items.FIRE_CHARGE,
				ESItems.SUNSET_THORNBLOOM.get(),
				ESItems.THERMAL_SPRINGSTONE.get(),
				ESItems.THERMAL_SPRINGSTONE_INGOT.get()
			);
		tag(ESTags.Items.BLAZE_CRYSTALS)
			.add(
				ESItems.BLAZE_CRYSTAL.get(),
				ESItems.MANA_CRYSTAL.get()
			);
		tag(ESTags.Items.LIGHT_CRYSTAL_INGREDIENTS)
			.add(
				Items.SOUL_TORCH,
				Items.TORCHFLOWER,
				ESItems.STARLIGHT_TORCHFLOWER.get(),
				ESItems.ORBFLORA_LIGHT.get()
			);
		tag(ESTags.Items.LIGHT_CRYSTALS)
			.add(
				ESItems.LIGHT_CRYSTAL.get(),
				ESItems.MANA_CRYSTAL.get()
			);
		tag(ESTags.Items.WIP)
			.add(
				ESItems.BOARWARF_SPAWN_EGG.get(),
				ESItems.ASTRAL_GOLEM_SPAWN_EGG.get(),
				ESItems.FLARE_BRICK.get(),
				ESItems.FLARE_BRICKS.get(),
				ESItems.FLARE_BRICK_SLAB.get(),
				ESItems.FLARE_BRICK_STAIRS.get(),
				ESItems.FLARE_BRICK_WALL.get(),
				ESItems.CUT_FLARE_BRICKS.get(),
				ESItems.CUT_FLARE_BRICK_SLAB.get(),
				ESItems.CUT_FLARE_BRICK_STAIRS.get(),
				ESItems.CUT_FLARE_BRICK_WALL.get(),
				ESItems.FLARE_TILES.get(),
				ESItems.FLARE_TILE_SLAB.get(),
				ESItems.FLARE_TILE_STAIRS.get(),
				ESItems.FLARE_TILE_WALL.get(),
				ESItems.CUT_FLARE_TILES.get(),
				ESItems.CUT_FLARE_TILE_SLAB.get(),
				ESItems.CUT_FLARE_TILE_STAIRS.get(),
				ESItems.CUT_FLARE_TILE_WALL.get(),
				ESItems.CHISELED_FLARE_PILLAR.get(),
				ESItems.SOLAR_EGG.get(),
				ESItems.DUSK_GLASS.get(),
				ESItems.DUSK_LIGHT.get(),
				ESItems.REINFORCED_DUSK_LIGHT.get(),
				ESItems.DUSK_EMITTER.get(),
				ESItems.DUSK_LOCKBOX.get(),
				ESItems.FLARE_SPAWNER.get(),
				ESItems.ECLIPSE_CORE.get(),
				ESItems.BROKEN_DOOMEDEN_BONE.get(),
				ESItems.BONEMORE.get(),
				ESItems.BOW_OF_BLOOD.get(),
				ESItems.LIVING_ARM.get(),
				ESItems.DOOMED_TORCH.get(),
				ESItems.DOOMED_REDSTONE_TORCH.get(),
				ESItems.DOOMEDEN_CARRION.get(),
				ESItems.ROTTEN_HAM.get(),
				ESItems.EYE_OF_DOOM.get(),
				ESItems.DOOMEDEN_RAG.get(),
				ESItems.FLESH_GRINDER.get(),
				ESItems.DOOMEDEN_RAPIER.get(),
				ESItems.DOOMEDEN_BRICKS.get(),
				ESItems.DOOMEDEN_BRICK_SLAB.get(),
				ESItems.DOOMEDEN_BRICK_STAIRS.get(),
				ESItems.DOOMEDEN_BRICK_WALL.get(),
				ESItems.POLISHED_DOOMEDEN_BRICKS.get(),
				ESItems.POLISHED_DOOMEDEN_BRICK_SLAB.get(),
				ESItems.POLISHED_DOOMEDEN_BRICK_STAIRS.get(),
				ESItems.POLISHED_DOOMEDEN_BRICK_WALL.get(),
				ESItems.DOOMEDEN_TILES.get(),
				ESItems.DOOMEDEN_TILE_SLAB.get(),
				ESItems.DOOMEDEN_TILE_STAIRS.get(),
				ESItems.DOOMEDEN_TILE_WALL.get(),
				ESItems.CHISELED_POLISHED_DOOMEDEN_BRICKS.get(),
				ESItems.CHARGED_CHISELED_POLISHED_DOOMEDEN_BRICKS.get(),
				ESItems.DOOMEDEN_LIGHT.get(),
				ESItems.DOOMEDEN_KEYHOLE.get(),
				ESItems.REDSTONE_DOOMEDEN_KEYHOLE.get(),
				ESItems.STELLAR_RACK.get(),
				ESItems.ENCHANTED_GRIMSTONE_BRICKS.get()
			);
		// mc tags
		copy(BlockTags.LOGS, ItemTags.LOGS);
		copy(BlockTags.LOGS_THAT_BURN, ItemTags.LOGS_THAT_BURN);
		copy(BlockTags.SAPLINGS, ItemTags.SAPLINGS);
		copy(BlockTags.LEAVES, ItemTags.LEAVES);
		copy(BlockTags.PLANKS, ItemTags.PLANKS);
		copy(BlockTags.WOODEN_FENCES, ItemTags.WOODEN_FENCES);
		copy(BlockTags.WOODEN_SLABS, ItemTags.WOODEN_SLABS);
		copy(BlockTags.SLABS, ItemTags.SLABS);
		copy(BlockTags.WOODEN_STAIRS, ItemTags.WOODEN_STAIRS);
		copy(BlockTags.STAIRS, ItemTags.STAIRS);
		copy(BlockTags.WOODEN_BUTTONS, ItemTags.WOODEN_BUTTONS);
		copy(BlockTags.WALLS, ItemTags.WALLS);
		copy(BlockTags.WOODEN_PRESSURE_PLATES, ItemTags.WOODEN_PRESSURE_PLATES);
		copy(BlockTags.WOODEN_DOORS, ItemTags.WOODEN_DOORS);
		copy(BlockTags.WOODEN_TRAPDOORS, ItemTags.WOODEN_TRAPDOORS);
		copy(BlockTags.STANDING_SIGNS, ItemTags.SIGNS);
		copy(BlockTags.CEILING_HANGING_SIGNS, ItemTags.HANGING_SIGNS);
		copy(BlockTags.SAND, ItemTags.SAND);
		copy(BlockTags.SMELTS_TO_GLASS, ItemTags.SMELTS_TO_GLASS);
		copy(BlockTags.SMALL_FLOWERS, ItemTags.SMALL_FLOWERS);
		copy(BlockTags.TALL_FLOWERS, ItemTags.TALL_FLOWERS);
		copy(BlockTags.CANDLES, ItemTags.CANDLES);
		// enchantables
		tag(ItemTags.DURABILITY_ENCHANTABLE)
			.add(
				ESItems.STARFALL_LONGBOW.get(),
				ESItems.DEEPSILVER_BRUSH.get(),
				ESItems.UNREALIUM_CROSSBOW.get(),
				ESItems.MALARITE_SPEAR.get(),
				ESItems.PUNGENCY_FRUIT_SPEAR.get(),
				ESItems.SEEDS_LAUNCHER.get(),
				ESItems.STARFIRE_CROSSBOW.get(),
				ESItems.FLOWGLAZE_BOW.get(),
				ESItems.SALTPETER_MATCHBOX.get(),
				ESItems.GLISTERING_BOW.get(),
				ESItems.MECHANICAL_CROSSBOW.get(),
				ESItems.CRYSTAL_CROSSBOW.get(),
				ESItems.WILTED_CROSSBOW.get(),
				ESItems.MOONRING_BOW.get(),
				ESItems.WAND_OF_TELEPORTATION.get(),
				ESItems.CHAIN_OF_SOULS.get(),
				ESItems.CRESCENT_SPEAR.get()
			)
			.addTags(
				ESTags.Items.SCYTHES,
				ESTags.Items.SICKLES,
				ESTags.Items.HAMMERS,
				ESTags.Items.BOOMERANGS,
				ESTags.Items.WHIPS,
				ESTags.Items.SMALL_SHIELDS
			);
		tag(ItemTags.BOW_ENCHANTABLE)
			.add(
				ESItems.STARFALL_LONGBOW.get(),
				ESItems.FLOWGLAZE_BOW.get(),
				ESItems.GLISTERING_BOW.get(),
				ESItems.MOONRING_BOW.get(),
				ESItems.BOW_OF_BLOOD.get()
			);
		tag(ItemTags.CROSSBOW_ENCHANTABLE)
			.add(
				ESItems.UNREALIUM_CROSSBOW.get(),
				ESItems.STARFIRE_CROSSBOW.get(),
				ESItems.MECHANICAL_CROSSBOW.get(),
				ESItems.CRYSTAL_CROSSBOW.get(),
				ESItems.WILTED_CROSSBOW.get()
			);
		tag(ItemTags.SWORD_ENCHANTABLE)
			.add(
				ESItems.CRESCENT_SPEAR.get()
			)
			.addTag(ESTags.Items.SCYTHE_ENCHANTABLE);
		tag(ItemTags.SHARP_WEAPON_ENCHANTABLE)
			.add(
				ESItems.MALARITE_SPEAR.get(),
				ESItems.PUNGENCY_FRUIT_SPEAR.get(),
				ESItems.CRESCENT_SPEAR.get()
			)
			.addTag(ESTags.Items.SCYTHE_ENCHANTABLE);
		tag(ItemTags.WEAPON_ENCHANTABLE)
			.addTags(
				ESTags.Items.HAMMER_ENCHANTABLE,
				ESTags.Items.BOOMERANG_ENCHANTABLE,
				ESTags.Items.WHIP_ENCHANTABLE
			);
		tag(ItemTags.FIRE_ASPECT_ENCHANTABLE)
			.add(
				ESItems.CRESCENT_SPEAR.get()
			)
			.addTags(
				ESTags.Items.SCYTHE_ENCHANTABLE,
				ESTags.Items.HAMMER_ENCHANTABLE,
				ESTags.Items.BOOMERANG_ENCHANTABLE
			);
		tag(ItemTags.BOATS)
			.add(
				ESItems.LUNAR_BOAT.get(),
				ESItems.NORTHLAND_BOAT.get(),
				ESItems.BANYIN_BOAT.get(),
				ESItems.SCARLET_BOAT.get(),
				ESItems.TORREYA_BOAT.get(),
				ESItems.JINGLESTEM_RAFT.get(),
				ESItems.CRADLEWOOD_BOAT.get()
			);
		tag(ItemTags.CHEST_BOATS)
			.add(
				ESItems.LUNAR_CHEST_BOAT.get(),
				ESItems.NORTHLAND_CHEST_BOAT.get(),
				ESItems.BANYIN_CHEST_BOAT.get(),
				ESItems.SCARLET_CHEST_BOAT.get(),
				ESItems.TORREYA_CHEST_BOAT.get(),
				ESItems.JINGLESTEM_CHEST_RAFT.get(),
				ESItems.CRADLEWOOD_CHEST_BOAT.get()
			);
		tag(ItemTags.FREEZE_IMMUNE_WEARABLES)
			.add(
				ESItems.THERMAL_SPRINGSTONE_HELMET.get(),
				ESItems.THERMAL_SPRINGSTONE_CHESTPLATE.get(),
				ESItems.THERMAL_SPRINGSTONE_LEGGINGS.get(),
				ESItems.THERMAL_SPRINGSTONE_BOOTS.get(),
				ESItems.GLACITE_HELMET.get(),
				ESItems.GLACITE_CHESTPLATE.get(),
				ESItems.GLACITE_LEGGINGS.get(),
				ESItems.GLACITE_BOOTS.get()
			);
		tag(ItemTags.MEAT)
			.add(
				ESItems.ROTTEN_FLESH_JERKY.get(),
				ESItems.ROOKFISH.get(),
				ESItems.COOKED_ROOKFISH.get(),
				ESItems.LUMINOFISH.get(),
				ESItems.COOKED_LUMINOFISH.get(),
				ESItems.LUMINARIS.get(),
				ESItems.COOKED_LUMINARIS.get(),
				ESItems.AURORA_DEER_STEAK.get(),
				ESItems.COOKED_AURORA_DEER_STEAK.get(),
				ESItems.RATLIN_MEAT.get(),
				ESItems.COOKED_RATLIN_MEAT.get(),
				ESItems.SHADOW_SNAIL_MEAT.get(),
				ESItems.COOKED_SHADOW_SNAIL_MEAT.get(),
				ESItems.DOOMEDEN_CARRION.get()
			);
		tag(ItemTags.HEAD_ARMOR)
			.add(
				ESItems.THERMAL_SPRINGSTONE_HELMET.get(),
				ESItems.GLACITE_HELMET.get(),
				ESItems.STARLIT_DIAMOND_HELMET.get(),
				ESItems.DEEPSILVER_HELMET.get(),
				ESItems.UNREALIUM_HELMET.get(),
				ESItems.AMARAMBER_MASK.get(),
				ESItems.ALCHEMIST_MASK.get(),
				ESItems.AETHERSENT_HOOD.get(),
				ESItems.AIR_SAC_MASK.get()
			);
		tag(ItemTags.CHEST_ARMOR)
			.add(
				ESItems.AETHERSENT_CAPE.get(),
				ESItems.THERMAL_SPRINGSTONE_CHESTPLATE.get(),
				ESItems.GLACITE_CHESTPLATE.get(),
				ESItems.STARLIT_DIAMOND_CHESTPLATE.get(),
				ESItems.DEEPSILVER_CHESTPLATE.get(),
				ESItems.UNREALIUM_CHESTPLATE.get(),
				ESItems.AMARAMBER_CHESTPLATE.get(),
				ESItems.ALCHEMIST_ROBE.get()
			);
		tag(ItemTags.LEG_ARMOR)
			.add(
				ESItems.AETHERSENT_BOTTOMS.get(),
				ESItems.THERMAL_SPRINGSTONE_LEGGINGS.get(),
				ESItems.GLACITE_LEGGINGS.get(),
				ESItems.STARLIT_DIAMOND_LEGGINGS.get(),
				ESItems.DEEPSILVER_LEGGINGS.get(),
				ESItems.UNREALIUM_LEGGINGS.get()
			);
		tag(ItemTags.FOOT_ARMOR)
			.add(
				ESItems.AETHERSENT_BOOTS.get(),
				ESItems.THERMAL_SPRINGSTONE_BOOTS.get(),
				ESItems.GLACITE_BOOTS.get(),
				ESItems.STARLIT_DIAMOND_BOOTS.get(),
				ESItems.DEEPSILVER_BOOTS.get(),
				ESItems.UNREALIUM_BOOTS.get(),
				ESItems.AIR_SAC_BOOTS.get()
			);
		tag(ItemTags.SWORDS)
			.add(
				ESItems.RAGE_OF_STARS.get(),
				ESItems.THERMAL_SPRINGSTONE_SWORD.get(),
				ESItems.GLACITE_SWORD.get(),
				ESItems.STARLIT_DIAMOND_SWORD.get(),
				ESItems.DEEPSILVER_SWORD.get(),
				ESItems.UNREALIUM_SWORD.get(),
				ESItems.MALARITE_SWORD.get(),
				ESItems.STARFIRE_SWORD.get(),
				ESItems.FLOWGLAZE_SWORD.get(),
				ESItems.AMARAMBER_SWORD.get(),
				ESItems.SHATTERED_SWORD.get(),
				ESItems.DAGGER_OF_HUNGER.get(),
				ESItems.GLISTERING_SWORD.get(),
				ESItems.ENERGY_SWORD.get(),
				ESItems.DOOMEDEN_RAPIER.get()
			)
			.addTag(ESTags.Items.GREATSWORDS);
		tag(ItemTags.PICKAXES)
			.add(
				ESItems.THERMAL_SPRINGSTONE_PICKAXE.get(),
				ESItems.THERMAL_SPRINGSTONE_HAMMER.get(),
				ESItems.GLACITE_PICKAXE.get(),
				ESItems.STARLIT_DIAMOND_PICKAXE.get(),
				ESItems.DEEPSILVER_PICKAXE.get(),
				ESItems.UNREALIUM_PICKAXE.get(),
				ESItems.MALARITE_PICKAXE.get(),
				ESItems.STARFIRE_PICKAXE.get(),
				ESItems.STARFIRE_HAMMER.get(),
				ESItems.FLOWGLAZE_PICKAXE.get(),
				ESItems.AMARAMBER_PICKAXE.get(),
				ESItems.GLISTERING_MORNING_STAR.get(),
				ESItems.UNDERMINER.get(),
				ESItems.GRAVITY_PICKAXE.get()
			);
		tag(ItemTags.CLUSTER_MAX_HARVESTABLES)
			.add(
				ESItems.THERMAL_SPRINGSTONE_PICKAXE.get(),
				ESItems.THERMAL_SPRINGSTONE_HAMMER.get(),
				ESItems.GLACITE_PICKAXE.get(),
				ESItems.STARLIT_DIAMOND_PICKAXE.get(),
				ESItems.DEEPSILVER_PICKAXE.get(),
				ESItems.UNREALIUM_PICKAXE.get(),
				ESItems.MALARITE_PICKAXE.get(),
				ESItems.STARFIRE_PICKAXE.get(),
				ESItems.STARFIRE_HAMMER.get(),
				ESItems.FLOWGLAZE_PICKAXE.get(),
				ESItems.AMARAMBER_PICKAXE.get(),
				ESItems.GLISTERING_MORNING_STAR.get(),
				ESItems.UNDERMINER.get(),
				ESItems.GRAVITY_PICKAXE.get()
			);
		tag(ItemTags.AXES)
			.add(
				ESItems.THERMAL_SPRINGSTONE_AXE.get(),
				ESItems.GLACITE_AXE.get(),
				ESItems.STARLIT_DIAMOND_AXE.get(),
				ESItems.DEEPSILVER_AXE.get(),
				ESItems.UNREALIUM_AXE.get(),
				ESItems.MALARITE_AXE.get(),
				ESItems.PUNGENCY_FRUIT_AXE.get(),
				ESItems.STARFIRE_AXE.get(),
				ESItems.FLOWGLAZE_AXE.get(),
				ESItems.AMARAMBER_AXE.get()
			);
		tag(ItemTags.HOES)
			.add(
				ESItems.THERMAL_SPRINGSTONE_HOE.get(),
				ESItems.GLACITE_HOE.get(),
				ESItems.STARLIT_DIAMOND_HOE.get(),
				ESItems.DEEPSILVER_HOE.get(),
				ESItems.UNREALIUM_HOE.get(),
				ESItems.MALARITE_HOE.get(),
				ESItems.STARFIRE_HOE.get(),
				ESItems.FLOWGLAZE_HOE.get(),
				ESItems.AMARAMBER_HOE.get()
			)
			.addTags(
				ESTags.Items.SCYTHES,
				ESTags.Items.SICKLES
			);
		tag(ItemTags.SHOVELS)
			.add(
				ESItems.THERMAL_SPRINGSTONE_SHOVEL.get(),
				ESItems.GLACITE_SHOVEL.get(),
				ESItems.STARLIT_DIAMOND_SHOVEL.get(),
				ESItems.DEEPSILVER_SHOVEL.get(),
				ESItems.UNREALIUM_SHOVEL.get(),
				ESItems.MALARITE_SHOVEL.get(),
				ESItems.STARFIRE_SHOVEL.get(),
				ESItems.FLOWGLAZE_SHOVEL.get(),
				ESItems.AMARAMBER_SHOVEL.get()
			);
		tag(ItemTags.ARROWS)
			.add(
				ESItems.AETHERSENT_ARROW.get(),
				ESItems.GLACITE_ARROW.get(),
				ESItems.MALARITE_ARROW.get(),
				ESItems.AMARAMBER_ARROW.get(),
				ESItems.THIOQUARTZ_ARROW.get(),
				ESItems.VORACIOUS_ARROW.get(),
				ESItems.AIR_SAC_ARROW.get()
			);
		tag(ItemTags.TRIM_MATERIALS)
			.add(
				ESItems.STARCORE.get(),
				ESItems.RED_STARLIGHT_CRYSTAL_SHARD.get(),
				ESItems.BLUE_STARLIGHT_CRYSTAL_SHARD.get(),
				ESItems.AETHERSENT_INGOT.get(),
				ESItems.THERMAL_SPRINGSTONE_INGOT.get(),
				ESItems.GLACITE_SHARD.get(),
				ESItems.STARLIT_DIAMOND.get(),
				ESItems.DEEPSILVER_INGOT.get(),
				ESItems.UNREALIUM_INGOT.get(),
				ESItems.MALARITE.get(),
				ESItems.STARFIRE.get(),
				ESItems.FLOWGLAZE.get(),
				ESItems.AMARAMBER_INGOT.get(),
				ESItems.THIOQUARTZ_SHARD.get(),
				ESItems.GOLEM_STEEL_INGOT.get(),
				ESItems.TENACIOUS_PETAL.get(),
				ESItems.BROKEN_DOOMEDEN_BONE.get()
			);
		tag(ItemTags.TRIM_TEMPLATES)
			.add(
				ESItems.KEEPER_ARMOR_TRIM_SMITHING_TEMPLATE.get(),
				ESItems.FORGE_ARMOR_TRIM_SMITHING_TEMPLATE.get(),
				ESItems.BLOOMING_ARMOR_TRIM_SMITHING_TEMPLATE.get(),
				ESItems.TWINING_ARMOR_TRIM_SMITHING_TEMPLATE.get()
			);
		tag(ItemTags.STONE_TOOL_MATERIALS)
			.add(
				ESItems.GRIMSTONE.get(),
				ESItems.COBBLED_GRIMSTONE.get(),
				ESItems.VOIDSTONE.get(),
				ESItems.COBBLED_VOIDSTONE.get()
			);
		tag(ItemTags.STONE_CRAFTING_MATERIALS)
			.add(
				ESItems.GRIMSTONE.get(),
				ESItems.COBBLED_GRIMSTONE.get(),
				ESItems.VOIDSTONE.get(),
				ESItems.COBBLED_VOIDSTONE.get()
			);
		tag(ItemTags.CREEPER_IGNITERS)
			.add(
				ESItems.SALTPETER_MATCHBOX.get()
			);
	}
}